name: 'Release Chart'
inputs:
  name:
    description: "Name of the release asset."
    required: true

  version:
    description: "Version of the bitnami chart to build."
    default: ''

  comment-header:
    description: "Header line for the Release summary."
    default: ":rocket: :anchor: Build Release Chart"

  comment-enabled:
    description: "Release comment creation and update."
    default: "true"

  chart:
    description: "Path to the helm chart."
    required: true

  registry:
    description: "URL of the chart registry."
    required: true

  registry-user:
    description: "Username for the chart registry."
    required: true

  registry-project:
    description: "Project within chart registry."
    required: true

  registry-repo:
    description: "Repo within chart registry project."
    required: true

  cosign-public-key:
    description: "Public key for cosigning images."
    required: false

  registry-token:
    description: "Authentication token for the chart registry."
    required: true

  cosign-private-key:
    description: "Private key for cosigning charts."
    required: false

  cosign-password:
    description: "Private key password for cosigning charts."
    required: false

runs:
  using: "composite"
  steps:
    - name: install cosign
      if: inputs.cosign-public-key != ''
      uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2

    - name: login to container registry for cosign
      if: inputs.cosign-public-key != ''
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-token }}

    - name: install helm
      uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
      with:
        version: 'v3.15.1'

    - name: login to chart registry
      shell: bash
      run: |
        helm registry login \
          --username '${{ inputs.registry-user }}' \
          --password '${{ inputs.registry-token }}' \
          ${{ inputs.registry }}

    - name: create chart repo url
      shell: bash
      run: |
        CHART_PROJECT="${{ inputs.registry }}/${{ inputs.registry-project }}/chart"
        echo "CHART_PROJECT=$CHART_PROJECT" >> $GITHUB_ENV
        echo "CHART_REPO=$CHART_PROJECT/${{ inputs.registry-repo }}" >> $GITHUB_ENV

    - name: new release
      shell: bash
      run: |
        echo "${SUMMARY}" >> "$GITHUB_STEP_SUMMARY"
      env:
        SUMMARY: |
          #### ${{ inputs.comment-header }} - ${{ inputs.name }} - :label: Commit: ${{ github.sha }}
          :label: New version will be ${{ inputs.version }}

    - name: create tags
      shell: bash
      run: |
        echo "RELEASE_TAG=${{ inputs.version }}" >> $GITHUB_ENV

    - name: build release chart
      id: helm-release
      shell: bash
      run: |
        helm dependency update ${{ inputs.chart }}
        helm package ${{ inputs.chart }} --version ${{ env.RELEASE_TAG }}
        helm push ${{ inputs.registry-repo }}-${{ env.RELEASE_TAG }}.tgz oci://${{ env.CHART_PROJECT }}

    - name: build success
      if: steps.helm-release.outcome == 'success'
      shell: bash
      run: |
        echo "${SUMMARY}" >> "$GITHUB_STEP_SUMMARY"
      env:
        SUMMARY: |
          ```
          ${{ env.CHART_REPO }}:${{ env.RELEASE_TAG }}
          ```
          :hammer_and_wrench: Build Success  

    - name: build failure
      if: failure() && steps.helm-release.outcome == 'failure'
      shell: bash
      run: |
        echo "${SUMMARY}" >> "$GITHUB_STEP_SUMMARY"
      env:
        SUMMARY: ":x: Build Failure"

    - name: cosign release
      id: cosign-release
      if: inputs.cosign-public-key != '' && steps.helm-release.outcome == 'success'
      env:
        COSIGN_PRIVATE_KEY: ${{ inputs.cosign-private-key }}
        COSIGN_PASSWORD: ${{ inputs.cosign-password }}
        COSIGN_PUBLIC_KEY: ${{ inputs.cosign-public-key }}
      shell: bash
      run: |
        cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${CHART_REPO}:${RELEASE_TAG}"
        cosign verify --key env://COSIGN_PUBLIC_KEY "${CHART_REPO}:${RELEASE_TAG}"

    - name: cosign success
      if: steps.cosign-release.outcome == 'success'
      shell: bash
      run: |
        echo "${SUMMARY}" >> "$GITHUB_STEP_SUMMARY"
      env:
        SUMMARY: ":black_nib: Cosign Success  "

    - name: cosign error
      if: failure() && steps.cosign-release.outcome == 'failure'
      shell: bash
      run: |
        echo "${SUMMARY}" >> "$GITHUB_STEP_SUMMARY"
      env:
        SUMMARY: ":x: Cosign Failure"

    - name: github release
      id: release
      if: steps.helm-release.outcome == 'success' && steps.cosign-release.outcome != 'failure'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
      with:
        retries: 3
        github-token: ${{ github.token }}
        script: |
          try {
            console.log("Attempting to create release...");
            github.rest.repos.createRelease({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              tag_name: "${{ inputs.name }}/${{ inputs.version }}",
              target_commitish: "${{ github.sha }}",
              body: "",
              name: "${{ inputs.name }}/${{ inputs.version }}"
            });
          } catch (error) {
            console.log(error);
            console.log("Failed to create release...");
            
            
            
          }

    - name: release success
      if: steps.release.outcome == 'success'
      shell: bash
      run: |
        echo "${SUMMARY}" >> "$GITHUB_STEP_SUMMARY"
      env:
        SUMMARY: |
          ```
          ${{ inputs.name }}/${{ inputs.version }}
          ```
          :hammer_and_wrench: Github Release Success  

    - name: release error
      if: failure() && steps.release.outcome == 'failure'
      shell: bash
      run: |
        echo "${SUMMARY}" >> "$GITHUB_STEP_SUMMARY"
      env:
        SUMMARY: ":x: Github Release Failure"

    - name: determine release
      id: determine-release
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          var inputs = ${{ toJSON(inputs) }};

          var result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,  
            commit_sha: context.sha,
          });

          if (result.data.length > 0) {
            if (result.data.length > 1) {
              core.warning("Found multiple pull requests associated with the current commit!");
            }

            for (let i = 0; i < result.data.length; i++) {
              var pr = result.data[i];
              core.debug(JSON.stringify(pr));

              core.info("Found pull request " + pr.number + " which created the current commit " + context.sha);
              core.setOutput("pr-number", pr.number);

              return;
            }
          }

          core.setFailed("Could not find pr to extract labels from.");

    - name: find pr comment
      uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3
      if: inputs.comment-enabled == 'true'
      id: find-pr-comment
      with:
        issue-number: ${{ steps.determine-release.outputs.pr-number }}
        body-includes: ${{ inputs.comment-header }} - ${{ inputs.name }}
        comment-author: "github-actions[bot]"

    - name: comment on release success
      id: release-pr-comment
      if: inputs.comment-enabled == 'true'
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
      with:
        comment-id: ${{ steps.find-pr-comment.outputs.comment-id }}
        issue-number: ${{ steps.determine-release.outputs.pr-number }}
        edit-mode: replace
        body: |
          #### ${{ inputs.comment-header }} - ${{ inputs.name }} - :label: Commit: ${{ github.sha }} - :gear: Workflow: [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          ```
          ${{ inputs.name }}/${{ inputs.version }}
          ${{ env.CHART_REPO }}:${{ env.RELEASE_TAG }}
          ```

    - name: error
      if: failure()
      shell: bash
      run: |
        echo "${SUMMARY}" >> "$GITHUB_STEP_SUMMARY"
      env:
        SUMMARY: |
          ---
          :x: An error occurred during execution! Check the workflow run logs for details!
