# Release branches where trunk branches are merge-committed to trigger releases

#release:
#- base-branch:
#  - 'release/.+'
#  - 'maintenance/.+/release/[0-9]+\.([0-9]+|x)\.x'

# Trunk branches where changes are collected before assets are released

#trunk:
#- base-branch:
#  - 'main'
#  - 'maintenance/.+/trunk/[0-9]+\.([0-9]+|x)\.x'

# Label any maintenance branch, trunk and release

maintenance:
- base-branch:
  - 'maintenance/.+/.+/[0-9]+\.([0-9]+|x)\.x'

# Label PRs into the main branch

#main:
#- base-branch:
#  - 'main'

# Labels for PRs on asset specific branches

containers:
- base-branch:
  - '.+/containers(/.+)?'

charts:
- base-branch:
  - '.+/charts(/.+)?'

pr-title-commitlint:
- base-branch:
  - '.+/pr-title-commitlint(/.+)?'

pr-labeler:
- base-branch:
  - '.+/pr-labeler(/.+)?'
