name: 'Flake8-nb'
inputs:

  config-file:
    description: "Path to the flake8-nb config file, relative to the repo root."
    required: true

  source-path:
    description: "Path to the top-level folder containing code to lint."
    required: true

runs:
  using: "composite"
  steps:
    - name: clone repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: install python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.12'

    - name: install flake8-nb
      shell: bash
      run: pip install flake8-nb

    - name: install flake8 annotations
      uses: rbialon/flake8-annotations@48819b39d57c621b5a64a1cdce40a5caa6a43b89 #v1.1

    - name: run flake8-nb
      shell: bash
      run: |
        flake8_nb --count --statistics --config $FLAKE8_CONFIG $SOURCE_PATH
      env:
        FLAKE8_CONFIG: ${{ inputs.config-file }}
        SOURCE_PATH: ${{ inputs.source-path }}