name: 'PR and Release Chart'
inputs:
  name:
    description: "Name of the release asset."
    required: true

  version:
    description: "Version of the bitnami chart to build."
    default: ''

  test-command:
    description: "Command to test the chart named $CHART."
    default: ''

  registry:
    description: "URL of the chart registry."
    required: true

  registry-user:
    description: "Username for the chart registry."
    required: true

  registry-project:
    description: "Project within chart registry."
    required: true

  cosign-public-key:
    description: "Public key for cosigning images."
    required: false

  registry-token:
    description: "Authentication token for the chart registry."
    required: true

  cosign-private-key:
    description: "Private key for cosigning charts."
    required: false

  cosign-password:
    description: "Private key password for cosigning charts."
    required: false

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        repository: "bitnami/charts"
        ref: "${{ inputs.name }}/${{ inputs.version }}"

    - if: github.event_name == 'pull_request'
      uses: SwanseaUniversityMedical/workflows/.github/actions/pr-chart@v1.0.4-pr-chart-action
      with:
        name: ${{ inputs.name }}-chart
        comment-enabled: "true"
        registry: ${{ inputs.registry }}
        registry-user: ${{ inputs.registry-user }}
        registry-project: ${{ inputs.registry-project }}
        registry-repo: ${{ inputs.name }}
        registry-token: ${{ inputs.registry-token }}
        cosign-public-key: ${{ inputs.cosign-public-key }}
        cosign-private-key: ${{ inputs.cosign-private-key }}
        cosign-password: ${{ inputs.cosign-password }}
        chart: "bitnami/${{ inputs.name }}"
        test-command: ${{ inputs.test-command }}

    - if: github.event_name == 'push'
      uses: SwanseaUniversityMedical/workflows/.github/actions/bitnami-release-chart@feat/bitnami-workflows
      with:
        name: ${{ inputs.name }}
        version: ${{ inputs.version }}
        comment-enabled: "true"
        registry: ${{ inputs.registry }}
        registry-user: ${{ inputs.registry-user }}
        registry-project: ${{ inputs.registry-project }}
        registry-repo: ${{ inputs.name }}
        registry-token: ${{ inputs.registry-token }}
        cosign-public-key: ${{ inputs.cosign-public-key }}
        cosign-private-key: ${{ inputs.cosign-private-key }}
        cosign-password: ${{ inputs.cosign-password }}
        chart: "bitnami/${{ inputs.name }}"
