name: 'Bulk PR and Release Chart'
inputs:
  name:
    description: "Name of the release asset."
    required: true

  chart:
    description: "Path to the helm chart."
    required: true

  comment-pr:
    description: "PR comment creation and update."
    default: "false"

  comment-release:
    description: "Release comment creation and update."
    default: "true"

  test-command:
    description: "Command to test the chart named $CHART."
    default: ''

  registry:
    description: "URL of the chart registry."
    required: true

  registry-user:
    description: "Username for the chart registry."
    required: true

  registry-project:
    description: "Project within chart registry."
    required: true

  registry-repo:
    description: "Repo within chart registry project."
    required: true

  release-info:
    description: "Release information json blob."
    required: true

  notation-cert:
    description: "Public key for notation signing images."
    required: true

  registry-token:
    description: "Authentication token for the chart registry."
    required: true

  notation-key:
    description: "Private key for notation signing charts."
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - if: github.event_name == 'pull_request'
      uses: SwanseaUniversityMedical/workflows/.github/actions/pr-chart@fix/cosign-tlog
      with:
        name: ${{ inputs.name }}
        comment-enabled: ${{ inputs.comment-pr }}
        label-eligible: 'false'
        registry: ${{ inputs.registry }}
        registry-user: ${{ inputs.registry-user }}
        registry-project: ${{ inputs.registry-project }}
        registry-repo: ${{ inputs.registry-repo }}
        notation-cert: ${{ inputs.notation-cert }}
        chart: ${{ inputs.chart }}
        test-command: ${{ inputs.test-command }}
        notation-key: ${{ inputs.notation-key }}

        registry-token: ${{ inputs.registry-token }}

    - if: github.event_name == 'push'
      uses: SwanseaUniversityMedical/workflows/.github/actions/bulk-release-chart@fix/cosign-tlog
      with:
        name: ${{ inputs.name }}
        comment-enabled: ${{ inputs.comment-release }}
        registry: ${{ inputs.registry }}
        registry-user: ${{ inputs.registry-user }}
        registry-project: ${{ inputs.registry-project }}
        registry-repo: ${{ inputs.registry-repo }}
        notation-cert: ${{ inputs.notation-cert }}
        chart: ${{ inputs.chart }}
        test-command: ${{ inputs.test-command }}
        release-info: ${{ inputs.release-info }}
        notation-key: ${{ inputs.notation-key }}

        registry-token: ${{ inputs.registry-token }}
