name: 'Ruff'
inputs:

  config-file:
    description: "Path to the ruff config file, relative to the repo root."
    required: true

  source-path:
    description: "Path to the top-level folder containing code to lint."
    required: true

runs:
  using: "composite"
  steps:
    - name: clone repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: install python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.12'

    - name: install ruff
      shell: bash
      run: pip install ruff

    - name: run ruff
      shell: bash
      run: |
        ruff check --output-format=github --config $RUFF_CONFIG $SOURCE_PATH
      env:
        RUFF_CONFIG: ${{ inputs.config-file }}
        SOURCE_PATH: ${{ inputs.source-path }}