name: 'SonarQube'
inputs:

  project-context:
    description: "Path to the root dir of the project."
    default: '.'

  sonar-url:
    description: "URL of the sonarqube sever."
    required: true

  sonar-token:
    description: "Authentication token for sonarqube."
    required: true

  project-key:
    description: "SonarQube Project Key"
    required: true

  sonar-exclusions:
    description: "Exclusion lists."
    default: '**.exe'

runs:
  using: "composite"
  steps:
    - name: clone repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: scan project
      uses: sonarsource/sonarqube-scan-action@v7.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-url }}
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.project-key }}
          -Dsonar.branch.name=${{ github.ref_name }}
          -Dsonar.exclusions=${{ inputs.sonar-exclusions }}