name: 'PR and Release Repo'
inputs:
  name:
    description: "Name of the release asset."
    required: true

  comment-release:
    description: "Release comment creation and update."
    default: "true"

  release-tag-format:
    description: "Semantic-release Github release tag format."
    default: '${version}'

outputs:
  release-info:
    description: "All release info in one json blob."
    value: ${{ toJSON(steps.release.outputs) }}

  new-release-published:
    description: "Semantic release output."
    value: ${{ steps.release.outputs.new-release-published }}

  release-version:
    description: "Semantic release output."
    value: ${{ steps.release.outputs.release-version }}

  git-tag:
    description: "Semantic release output."
    value: ${{ steps.release.outputs.git-tag }}

  pr-number:
    description: "Release PR number."
    value: ${{ steps.release.outputs.pr-number }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - id: create-release-labels
      uses: SwanseaUniversityMedical/workflows/.github/actions/create-release-labels@v3.0.0-create-release-labels-action
      with:
        name: ${{ inputs.name }}

    - name: add eligible label
      if: github.event_name == 'pull_request'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          var inputs = ${{ toJSON(inputs) }};
          var asset = inputs['name'];
          var eligible = `eligible: ${asset}`;

          try {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              labels: [eligible]
            });
          } catch (error) {
            console.log(error);
          }

    - id: release
      if: github.event_name == 'push'
      uses: SwanseaUniversityMedical/workflows/.github/actions/release-repo@v3.0.1-release-repo-action
      with:
        name: ${{ inputs.name }}
        release-tag-format: ${{ inputs.release-tag-format }}
