name: 'Bulk PR and Release Container'
inputs:
  name:
    description: "Name of the release asset."
    required: true

  comment-pr:
    description: "PR comment creation and update."
    default: "false"

  comment-release:
    description: "Release comment creation and update."
    default: "true"

  build-file:
    description: "Path to the container file."
    required: true

  build-context:
    description: "Path to the build root dir."
    default: '.'

  test-flags:
    description: "Arguments passed to docker run."
    default: ''

  test-args:
    description: "Arguments passed to the container."
    default: ''

  registry:
    description: "URL of the container registry."
    required: true

  registry-user:
    description: "Username for the container registry."
    required: true

  registry-repo:
    description: "Repo within container registry project."
    required: true

  release-info:
    description: "Release information json blob."
    required: true

  registry-extra-tag-command:
    description: "Extra tag to push release container."
    default: ''

  cosign-public-key:
    description: "Public key for cosigning images."
    required: false

  registry-token:
    description: "Authentication token for the container registry."
    required: true

  cosign-private-key:
    description: "Private key for cosigning images."
    required: false

  cosign-password:
    description: "Private key password for cosigning images."
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - if: github.event_name == 'pull_request'
      uses: SwanseaUniversityMedical/workflows/.github/actions/pr-container@v1.0.5-pr-container-action
      with:
        name: ${{ inputs.name }}
        comment-enabled: ${{ inputs.comment-pr }}
        registry: ${{ inputs.registry }}
        registry-user: ${{ inputs.registry-user }}
        registry-repo: ${{ inputs.registry-repo }}
        registry-token: ${{ inputs.registry-token }}
        build-file: ${{ inputs.build-file }}
        build-context: ${{ inputs.build-context }}
        test-flags: ${{ inputs.test-flags }}
        test-args: ${{ inputs.test-args }}
        cosign-public-key: ${{ inputs.cosign-public-key }}
        cosign-private-key: ${{ inputs.cosign-private-key }}
        cosign-password: ${{ inputs.cosign-password }}

    - if: github.event_name == 'push'
      uses: SwanseaUniversityMedical/workflows/.github/actions/bulk-release-container@v1.0.6-bulk-release-container-action
      with:
        name: ${{ inputs.name }}
        comment-enabled: ${{ inputs.comment-release }}
        registry: ${{ inputs.registry }}
        registry-user: ${{ inputs.registry-user }}
        registry-repo: ${{ inputs.registry-repo }}
        registry-token: ${{ inputs.registry-token }}
        registry-extra-tag-command: ${{ inputs.registry-extra-tag-command }}
        release-info: ${{ inputs.release-info }}
        build-file: ${{ inputs.build-file }}
        build-context: ${{ inputs.build-context }}
        test-flags: ${{ inputs.test-flags }}
        test-args: ${{ inputs.test-args }}
        cosign-public-key: ${{ inputs.cosign-public-key }}
        cosign-private-key: ${{ inputs.cosign-private-key }}
        cosign-password: ${{ inputs.cosign-password }}

