name: 'Renovate'
inputs:

  config:
    description: "Path to the renovate config file within the repo."
    default: ".github/renovate.js"

  token:
    description: "Github token to run renovate with."

runs:
  using: "composite"
  steps:
    - name: clone repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{ inputs.config }}

    - name: make cache directory
      shell: bash
      run: |
        mkdir -p /tmp/renovate/cache

    - name: renovate cache
      uses: actions/cache@v4
      with:
        path: /tmp/renovate
        key: ${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.ref }}-
          ${{ github.workflow }}-

    - name: dump cache directory
      shell: bash
      run: |
        sudo ls -laR /tmp/renovate

    - name: current user
      shell: bash
      id: id
      run: |
        echo "user=$(id -u)" >> $GITHUB_OUTPUT
        echo "group=$(id -g)" >> $GITHUB_OUTPUT
          
    - name: run renovate bot
      uses: renovatebot/github-action@v41.0.12
      with:
        renovate-image: "harbor.ukserp.ac.uk/github-workflows/renovate"
        # TODO annotate this for renovate to bump... the irony is not lost on me...
        renovate-version: "39.157.0"
        configurationFile: ${{ inputs.config }}
        token: ${{ inputs.token }}
        env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|\\w+_PROXY)$"
        docker-user: "${{ steps.id.outputs.user }}:${{ steps.id.outputs.group }}"
        docker-volumes: "/tmp/renovate:/tmp/renovate"
      env:
        RENOVATE_BASE_DIR: "/tmp/renovate"
        RENOVATE_CACHE_DIR: "/tmp/renovate/cache"
        RENOVATE_REPOSITORY_CACHE: "enabled"
        RENOVATE_REPOSITORY_CACHE_TYPE: "local"
        RENOVATE_CACHE_PRIVATE_PACKAGES: "true"
        RENOVATE_LOG_FILE_LEVEL: "debug"

    - name: dump cache directory
      shell: bash
      run: |
        sudo ls -laR /tmp/renovate
        
