name: 'Renovate'
inputs:

  config:
    description: "Path to the renovate config file within the repo."
    default: ".github/renovate.js"

  token:
    description: "Github token to run renovate with."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        sparse-checkout: |
          ${{ inputs.config }}

    - name: run renovate bot
      uses: renovatebot/github-action@f5c3383cb7cbf7711d8b66b809375b2d5f4e2d1d # v42.0.2
      with:
        renovate-image: "harbor.ukserp.ac.uk/github-workflows/renovate"
        # TODO annotate this for renovate to bump... the irony is not lost on me...
        renovate-version: "39.254.3"
        configurationFile: ${{ inputs.config }}
        token: ${{ inputs.token }}
        env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|\\w+_PROXY)$"
