name: 'Renovate'
inputs:

  config:
    description: "Path to the renovate config file within the repo."
    default: ".github/renovate.js"

  token:
    description: "Github token to run renovate with."

  cache:
    description: "Paths to the cache directories renovate is configured to use. Specify one path per line. Set to '' to disable caching."
    default: "/tmp/renovate"

runs:
  using: "composite"
  steps:
    - name: clone repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{ inputs.config }}

    - name: cache renovate
      if: inputs.cache != ''
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache }}
        key: ${{ github.workflow }}-${{ github.ref }}
        restore-keys: |
          ${{ github.workflow }}-${{ github.ref }}
          ${{ github.workflow }}-
          
    - name: run renovate bot
      uses: renovatebot/github-action@v41.0.12
      with:
        renovate-image: "harbor.ukserp.ac.uk/github-workflows/renovate"
        # TODO annotate this for renovate to bump... the irony is not lost on me...
        renovate-version: "39.157.0"
        configurationFile: ${{ inputs.config }}
        token: ${{ inputs.token }}
        env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|\\w+_PROXY)$"
