name: 'Renovate'
inputs:

  config:
    description: "Path to the renovate config file within the repo."
    default: ".github/renovate.js"

  token:
    description: "Github token to run renovate with."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{ inputs.config }}

    - name: run renovate bot
      uses: renovatebot/github-action@08ed9fa83e24bfe6222557f9e221395c57972127 # v41.0.16
      with:
        renovate-image: "harbor.ukserp.ac.uk/github-workflows/renovate"
        # TODO annotate this for renovate to bump... the irony is not lost on me...
        renovate-version: "39.157.0"
        configurationFile: ${{ inputs.config }}
        token: ${{ inputs.token }}
        env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|\\w+_PROXY)$"
