on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      chart:
        description: "Path to the helm chart."
        required: true
        type: string

      chart-registry:
        description: "URL of the chart registry."
        required: true
        type: string

      chart-registry-user:
        description: "Username for the chart registry."
        required: true
        type: string

      chart-registry-project:
        description: "Project within chart registry."
        required: true
        type: string

      chart-registry-repo:
        description: "Repo within chart registry project."
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      chart-registry-token:
        description: "Authentication token for the chart registry."
        required: true

    outputs:

      registry:
        description: "URL of the chart registry."
        value: ${{ inputs.chart-registry }}

      project:
        description: "Project within chart registry."
        value: ${{ inputs.chart-registry-project }}

      repo:
        description: "Repo within chart registry project."
        value: ${{ inputs.chart-registry-repo }}

      digest:
        description: "Docker pull URI with digest."
        value: ${{ jobs.build-pr-chart.outputs.digest }}

      pr-tag:
        description: "Docker pull URI with pr tag."
        value: ${{ jobs.build-pr-chart.outputs.pr-tag }}

      pr-commit-tag:
        description: "Docker pull URI with pr and sha tag."
        value: ${{ jobs.build-pr-chart.outputs.pr-commit-tag }}

jobs:
  build-pr-chart:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: heavy

    outputs:
      digest: ${{ env.PR_COMMIT_TAG }}
      pr-tag: ${{ env.PR_TAG }}
      pr-commit-tag: ${{ env.PR_COMMIT_TAG }}

    steps:
      - name: build chart uri
        run: |
          echo "CHART_REPO=${{ inputs.chart-registry }}/${{ inputs.chart-registry-project }}/chart" >> $GITHUB_ENV

      - name: get short commit sha
        run: |
          echo "GITHUB_SHORT_SHA=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - name: create tags
        run: |
          echo "PR_TAG=0.0.0-pr.${{ github.event.pull_request.number }}" >> $GITHUB_ENV  
          echo "PR_COMMIT_TAG=0.0.0-pr.${{ github.event.pull_request.number }}_${{ env.GITHUB_SHORT_SHA }}" >> $GITHUB_ENV  

      - name: clone repo
        uses: actions/checkout@v3

      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'
          token: ${{ github.token }}

      - name: update chart dependencies
        run: |
          helm dependency update ${{ inputs.chart }}

      - name: login to chart registry
        run: |
          helm registry login \
            --username '${{ inputs.chart-registry-user }}' \
            --password '${{ secrets.chart-registry-token }}' \
            oci://${{ inputs.chart-registry }}

      - name: push charts
        run: |
          helm push ${{ inputs.chart }} --version $PR_TAG --app-version $PR_TAG oci://${{ env.CHART_REPO }}
          helm push ${{ inputs.chart }} --version $PR_COMMIT_TAG --app-version $PR_COMMIT_TAG oci://${{ env.CHART_REPO }}

      - name: annotate the ci run with chart tags
        run: >-
          echo "::notice title=Job: ${{ github.job }} / ${{ inputs.job-name }}::%0A
          Pushed PR chart assets!%0A
          - %0A
          helm registry login --username <user> --password <token> oci://${{ inputs.chart-registry }}%0A
          helm pull --version ${{ env.PR_TAG }} oci://${{ env.CHART_REPO }}/${{ inputs.chart-registry-repo }}%0A
          helm pull --version ${{ env.PR_COMMIT_TAG }} oci://${{ env.CHART_REPO }}/${{ inputs.chart-registry-repo }}"

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        continue-on-error: true
        if: failure()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            *${{ github.repository }}*\n
            *PR-${{ github.event.pull_request.number }} Update*\n
            ${{ inputs.status-failure }} job: ${{ github.job }} / ${{ inputs.job-name }}\n
            <https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|:octocat: Pull Request>\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>\n
            ```
            PR:       ${{ github.event.pull_request.title }}
            Branch:   ${{ github.head_ref }}
            Ref:      ${{ github.ref }}
            Sha:      ${{ github.event.pull_request.head.sha }}
            Workflow: ${{ github.workflow }}
            Run:      ${{ github.run_id }}
            ```