on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      command:
        description: "Command to build the container named $IMAGE."
        required: true
        type: string

      release-version:
        description: "Semver version of the release."
        required: true
        type: string

      registry:
        description: "URL of the container registry."
        required: true
        type: string

      registry-user:
        description: "Username for the container registry."
        required: true
        type: string

      registry-project:
        description: "Project within container registry."
        required: true
        type: string

      registry-repo:
        description: "Repo within container registry project."
        required: true
        type: string

      registry-tag-prefix:
        description: "Prefix to use when tagging container"
        required: true
        type: string

      registry-tag-suffix:
        description: "Suffix to use when tagging container"
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

      cosign-public-key:
        description: "Public key for cosigning images."
        required: false
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      registry-token:
        description: "Authentication token for the container registry."
        required: true

      cosign-private-key:
        description: "Private key for cosigning images."
        required: false

      cosign-password:
        description: "Private key password for cosigning images."
        required: false

    outputs:

      registry:
        description: "URL of the container registry."
        value: ${{ inputs.registry }}

      project:
        description: "Project within container registry."
        value: ${{ inputs.registry-project }}

      repo:
        description: "Repo within container registry project."
        value: ${{ inputs.registry-repo }}

      digest:
        description: "Docker pull URI with digest."
        value: ${{ jobs.build-release-container.outputs.digest }}

      rc-tag:
        description: "Docker pull URI with rc tag."
        value: ${{ jobs.build-release-container.outputs.rc-tag }}

jobs:
  build-release-container:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: heavy

    outputs:
      digest: ${{ env.DIGEST }}
      rc-tag: ${{ env.RC_TAG }}

    steps:
      - name: build image uri
        run: |
          echo "IMAGE=${{ inputs.registry }}/${{ inputs.registry-project }}/${{ inputs.registry-repo }}" >> $GITHUB_ENV

      - name: create tags
        run: |
          echo "RC_TAG=${{ env.IMAGE }}:rc-${{ inputs.registry-tag-prefix }}${{ inputs.release-version }}${{ inputs.registry-tag-suffix }}" >> $GITHUB_ENV 

      - name: clone repo
        uses: actions/checkout@v3

      - name: install cosign
        if: inputs.cosign-public-key != ''
        uses: sigstore/cosign-installer@v3.1.2

      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-user }}
          password: ${{ secrets.registry-token }}

      - name: build container
        run: ${{ inputs.command }}

      - name: tag container
        run: |
          docker tag ${{ env.IMAGE }} ${{ env.RC_TAG }}

      - name: push container
        run: |
          docker push ${{ env.RC_TAG }}

      - name: container digest
        id: digest
        run: |
          echo "DIGEST=`docker inspect --format='{{index .RepoDigests 0}}' ${{ env.RC_TAG }}`" >> $GITHUB_ENV

      - name: cosign image
        if: inputs.cosign-public-key != ''
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.cosign-private-key }}
          COSIGN_PASSWORD: ${{ secrets.cosign-password }}
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${{ env.DIGEST }}"

      - name: cosign verify image
        if: inputs.cosign-public-key != ''
        env:
          COSIGN_PUBLIC_KEY: ${{ inputs.cosign-public-key }}
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY "${{ env.DIGEST }}"

      - name: annotate the ci run with container tags
        run: >-
          echo "::notice title=Job: ${{ github.job }} / ${{ inputs.job-name }}::%0A
          Pushed release candidate container assets!%0A
          - %0A
          docker pull ${{ env.RC_TAG }}%0A
          docker pull ${{ env.DIGEST }}"

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        continue-on-error: true
        if: failure()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            *${{ github.repository }}*\n
            *Release ${{ github.ref }}*\n
            ${{ inputs.status-failure }} job: ${{ github.job }} / ${{ inputs.job-name }}\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>\n
            ```
            Ref:      ${{ github.ref }}\n
            Sha:      ${{ github.sha }}\n
            Workflow: ${{ github.workflow }}\n
            Run:      ${{ github.run_id }}
            ```
