on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      release-version:
        description: "Semver version of the release."
        required: true
        type: string

      chart:
        description: "Path to the helm chart."
        required: true
        type: string

      chart-registry:
        description: "URL of the chart registry."
        required: true
        type: string

      chart-registry-user:
        description: "Username for the chart registry."
        required: true
        type: string

      chart-registry-project:
        description: "Project within chart registry."
        required: true
        type: string

      chart-registry-repo:
        description: "Repo within chart registry project."
        required: true
        type: string

      chart-tag-suffix:
        description: "Suffix to use when tagging chart"
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      chart-registry-token:
        description: "Authentication token for the chart registry."
        required: true

    outputs:

      registry:
        description: "URL of the chart registry."
        value: ${{ inputs.chart-registry }}

      project:
        description: "Project within chart registry."
        value: ${{ inputs.chart-registry-project }}

      repo:
        description: "Repo within chart registry project."
        value: ${{ inputs.chart-registry-repo }}

      digest:
        description: "Docker pull URI with digest."
        value: ${{ jobs.build-release-chart.outputs.digest }}

      pr-tag:
        description: "Docker pull URI with pr tag."
        value: ${{ jobs.build-release-chart.outputs.pr-tag }}

      pr-commit-tag:
        description: "Docker pull URI with pr and sha tag."
        value: ${{ jobs.build-release-chart.outputs.pr-commit-tag }}

jobs:
  build-release-chart:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: heavy

    outputs:
      digest: ${{ env.RC_TAG }}
      rc-tag: ${{ env.RC_TAG }}

    steps:
      - name: build chart uri
        run: |
          echo "CHART_REPO=${{ inputs.chart-registry }}/${{ inputs.chart-registry-project }}/chart" >> $GITHUB_ENV

      - name: create tags
        run: |
          echo "RC_TAG=${{ inputs.release-version }}-rc${{ inputs.chart-tag-suffix }}" >> $GITHUB_ENV 

      - name: clone repo
        uses: actions/checkout@v3

      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'
          token: ${{ github.token }}

      - name: login to chart registry
        run: |
          helm registry login \
            --username '${{ inputs.chart-registry-user }}' \
            --password '${{ secrets.chart-registry-token }}' \
            oci://${{ inputs.chart-registry }}

      - name: update chart dependencies
        run: |
          helm dependency update ${{ inputs.chart }}

      - name: push charts
        run: |
          helm push ${{ inputs.chart }} --version ${{ env.RC_TAG }} --app-version ${{ env.RC_TAG }} oci://${{ env.CHART_REPO }}

      - name: annotate the ci run with chart tags
        run: >-
          echo "::notice title=Job: ${{ github.job }} / ${{ inputs.job-name }}::%0A
          Pushed release candidate chart assets!%0A
          - %0A
          helm registry login --username <user> --password <token> oci://${{ inputs.chart-registry }}%0A
          helm pull --version ${{ env.RC_TAG }} oci://${{ env.CHART_REPO }}"

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        continue-on-error: true
        if: failure()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            *${{ github.repository }}*\n
            *Release ${{ github.ref }}*\n
            ${{ inputs.status-failure }} job: ${{ github.job }} / ${{ inputs.job-name }}\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>\n
            ```
            Ref:      ${{ github.ref }}\n
            Sha:      ${{ github.sha }}\n
            Workflow: ${{ github.workflow }}\n
            Run:      ${{ github.run_id }}
            ```
