on:
  workflow_call:
    inputs:

      filters:
        description: "YAML dictionary of lists of path filters."
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

    outputs:

      changes:
        description: "JSON encoded dictionary of boolean change filters."
        value: ${{ jobs.changes.outputs.changes }}

jobs:
  changes:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: light

    outputs:
      changes: ${{ toJSON(steps.changes.outputs) }}

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: detect changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: ${{ inputs.filters }}

      - name: annotate the ci run with changes
        run: >-
          echo "::notice title=Job: ${{ github.job }}::%0A
          Changes: ${{ steps.changes.outputs.changes }}"

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        continue-on-error: true
        if: failure()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            *${{ github.repository }}*\n
            *Release ${{ github.ref }}*\n
            ${{ inputs.status-failure }} job: ${{ github.job }}\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>\n
            ```
            Ref:      ${{ github.ref }}\n
            Sha:      ${{ github.sha }}\n
            Workflow: ${{ github.workflow }}\n
            Run:      ${{ github.run_id }}
            ```
