# chart example

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/charts.yaml'
      - '.github/workflows/pr-and-release-chart.yaml'
      - '.github/actions/pr-chart/action.yaml'
      - '.github/actions/release-chart/action.yaml'
      - 'charts/helloworld/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/charts.yaml'
      - '.github/workflows/pr-and-release-chart.yaml'
      - '.github/actions/pr-chart/action.yaml'
      - '.github/actions/release-chart/action.yaml'
      - 'charts/helloworld/**'

permissions:
  # Permission needed to author a Github release
  contents: write
  # pull-request: write if you enable PR thread comments
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  chart-helloworld:
    # Build the helloworld chart and push it
    uses: ./.github/workflows/pr-and-release-chart.yaml
    with:
      job-name: chart-helloworld
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-project: ${{ vars.HARBOR_PROJECT }}
      registry-repo: helloworld
      release-tag-format: 'helloworld-${version}'
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      chart: charts/helloworld
      test-command: |
        helm template $CHART --values tests/charts/helloworld/values.yaml

    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      workflows-token: ${{ secrets.WORKFLOWS_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  workflows:
    # Release the workflows repo
    needs:
      - chart-helloworld
    if: ${{ success() && github.event_name == 'push' }}

    uses: ./.github/workflows/on-release-repo.yaml
    with:
      job-name: workflows-chart
      release-tag-format: 'charts-v${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}