name: Commit Lint PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-title-commitlint:
    if: ${{ success() && github.event_name == 'pull_request' }}
    uses: ./.github/workflows/pr-title-commitlint.yaml
