name: Commit Lint PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-title-commitlint:
    uses: ./.github/workflows/pr-title-commitlint.yaml
    with:
      runs-on: "k8s-dev-linux-default"
