on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/containers.yaml'
      - '.github/workflows/pr-and-release-container.yaml'
      - '.github/actions/pr-container/action.yaml'
      - '.github/actions/release-container/action.yaml'
      - 'containers/whalesay/**'
      - 'containers/whalesay2/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/containers.yaml'
      - '.github/workflows/pr-and-release-container.yaml'
      - '.github/actions/pr-container/action.yaml'
      - '.github/actions/release-container/action.yaml'
      - 'containers/whalesay/**'
      - 'containers/whalesay2/**'

permissions:
  # Permission needed to author a Github release
  contents: write
# pull-request: write if you enable PR thread comments
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  whalesay:
    uses: ./.github/workflows/pr-and-release-container.yaml
    with:
      job-name: container-whalesay
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: github-workflows/whalesay
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-file: containers/whalesay/Dockerfile
      build-context: containers/whalesay
      test-args: cowsay boo
      release-tag-format: 'whalesay-${version}'
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  whalesay2:
    # Build the whalesay2 container
    uses: ./.github/workflows/pr-and-release-container.yaml
    with:
      job-name: container-whalesay2
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: github-workflows/whalesay2
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      release-tag-format: 'whalesay2-${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-file: containers/whalesay2/Dockerfile
      build-context: containers/whalesay2
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  workflows:
      # Release the workflows repo
      needs:
        - whalesay
        - whalesay2
      if:  ${{ success() && github.event_name == 'push' }}

      uses: ./.github/workflows/on-release-repo.yaml
      with:
        job-name: workflows-container
        release-tag-format: 'containers-v${version}'
        slack-channel: ${{ vars.SLACK_CHANNEL }}
      secrets:
        slack-token: ${{ secrets.SLACK_TOKEN }}