on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/containers.yaml'
      - '.github/workflows/pr-and-release-container.yaml'
      - '.github/actions/pr-container/action.yaml'
      - '.github/actions/release-container/action.yaml'
      - 'containers/whalesay/**'
      - 'containers/aspnet/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/containers.yaml'
      - '.github/workflows/pr-and-release-container.yaml'
      - '.github/actions/pr-container/action.yaml'
      - '.github/actions/release-container/action.yaml'
      - 'containers/whalesay/**'
      - 'containers/aspnet/**'

permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  trino-container:
    uses: ./.github/workflows/pr-and-release-container.yaml
    with:
      job-name: trino-container
      comment-release: "true"
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: github-workflows/trino
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: containers/trino/Dockerfile
      build-context: containers/trino
      release-tag-format: 'v${version}-trino'
      registry-extra-tag-command: >-
        cat containers/trino/Dockerfile | grep -m 1 "ARG BASE_VERSION=" | cut -d "=" -f 2
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  whalesay-container:
    uses: ./.github/workflows/pr-and-release-container.yaml
    with:
      job-name: whalesay-container
      comment-pr: "true"
      comment-release: "true"
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: github-workflows/whalesay
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      build-file: containers/whalesay/Dockerfile
      build-context: containers/whalesay
      test-args: cowsay boo
      release-tag-format: 'v${version}-whalesay'
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  aspnet-container:
    # Build the aspnet container
    uses: ./.github/workflows/pr-and-release-container.yaml
    with:
      job-name: aspnet-container
      comment-pr: "false"
      comment-release: "true"
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: github-workflows/aspnet
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      release-tag-format: 'v${version}-aspnet'
      build-file: containers/aspnet/Dockerfile
      build-context: containers/aspnet
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}

  workflows:
      # Release the workflows repo
      needs:
        - whalesay-container
        - aspnet-container
        - trino-container
      if:  ${{ success() && github.event_name == 'push' }}

      uses: ./.github/workflows/on-release-repo.yaml
      with:
        job-name: workflows-container
        release-tag-format: 'v${version}-containers'
        slack-channel: ${{ vars.SLACK_CHANNEL }}
      secrets:
        slack-token: ${{ secrets.SLACK_TOKEN }}
