on:
  workflow_call:
    inputs:

      base-dir:
        description: "Path to the base dir for the scan."
        default: '.'
        type: string

      sonar-url:
        description: "URL of the sonarqube sever."
        required: true
        type: string

      project-key:
        description: "SonarQube Project Key"
        required: true
        type: string

      sonar-exclusions:
        description: "Exclusion lists."
        default: '**.exe'
        type: string

    secrets:
      sonar-token:
        description: "Authentication token for sonarqube."
        required: true
      
      sonar-root-cert:
        description: "Certificate for sonarqube server if needed."
        required: false


jobs:
  scan:
    runs-on:
      labels: [ self-hosted, linux, x64 ]
      group: sonar
    steps:
      - name: clone repo
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis.

      - name: scan project
        if: ${{ github.event_name != 'pull_request' }}
        uses: sonarsource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          SONAR_HOST_URL: ${{ inputs.sonar-url }}
          SONAR_ROOT_CERT: ${{ secrets.sonar-root-cert }}
        with:
          projectBaseDir: ${{ inputs.base-dir }}
          args: >
            -Dsonar.projectKey=${{ inputs.project-key }}
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.exclusions=${{ inputs.sonar-exclusions }}


      - name: scan project PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: sonarsource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          SONAR_HOST_URL: ${{ inputs.sonar-url }}
          SONAR_ROOT_CERT: ${{ secrets.sonar-root-cert }}
        with:
          projectBaseDir: ${{ inputs.base-dir }}
          args: >
            -Dsonar.projectKey=${{ inputs.project-key }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
            -Dsonar.exclusions=${{ inputs.sonar-exclusions }}
