name: Label PR

on:
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-labeler:
    uses: ./.github/workflows/pr-labeler.yaml
    with:
      runs-on: "feda-linux-default"
