name: PR Update

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  # Permission needed for the changes.yaml workflow to detect changes across the full PR branch
  # pull-request: write if you enable PR thread comments
  pull-requests: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  changes:
    # Detect which files have been changed on this PR's full history
    uses: ./.github/workflows/changes-pr.yaml
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      filters: |
        container-whalesay:
          - './.github/workflows/on-pr-update.yaml'
          - './.github/workflows/on-pr-update-container.yaml'
          - './.github/workflows/slack-pr-thread.yaml'
          - './.github/workflows/changes-pr.yaml'
          - './.github/workflows/build-pr-container.yaml'
          - './.github/workflows/test-pr-container.yaml'
          - './containers/whalesay/**'
        container-whalesay2:
          - './.github/workflows/on-pr-update.yaml'
          - './.github/workflows/on-pr-update-container.yaml'
          - './.github/workflows/slack-pr-thread.yaml'
          - './.github/workflows/changes-pr.yaml'
          - './.github/workflows/build-pr-container.yaml'
          - './.github/workflows/test-pr-container.yaml'
          - './containers/whalesay/**'
        chart-helloworld:
          - './.github/workflows/on-pr-update.yaml'
          - './.github/workflows/on-pr-update-chart.yaml'
          - './.github/workflows/slack-pr-thread.yaml'
          - './.github/workflows/changes-pr.yaml'
          - './.github/workflows/build-pr-chart.yaml'
          - './.github/workflows/test-pr-chart.yaml'
          - './charts/helloworld/**'
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  container-whalesay:
    # Build the whalesay container and push it as :pr-42 and :pr-42-fe45b3h
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).container-whalesay == 'true'
    uses: ./.github/workflows/on-pr-update-container.yaml
    with:
      job-name: container-whalesay
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: whalesay
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-command: |
        docker build -t $IMAGE -f containers/whalesay/Dockerfile containers/whalesay
      test-command: |
        docker run $IMAGE cowsay boo

    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  container-whalesay2:
    # Build the whalesay container and push it as :pr-42 and :pr-42-fe45b3h
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).container-whalesay2 == 'true'
    uses: ./.github/workflows/on-pr-update-container.yaml
    with:
      job-name: container-whalesay2
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: whalesay2
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-command: |
        docker build -t $IMAGE -f containers/whalesay2/Dockerfile containers/whalesay2
      test-command: |
        docker run $IMAGE cowsay boo

    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  chart-helloworld:
    # Build the helloworld chart and push it
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).chart-helloworld == 'true'
    uses: ./.github/workflows/on-pr-update-chart.yaml
    with:
      job-name: chart-helloworld
      chart-registry: ${{ vars.HARBOR_REGISTRY }}
      chart-registry-user: ${{ vars.HARBOR_USER }}
      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
      chart-registry-repo: helloworld
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      chart: charts/helloworld
      test-command: |
        helm template $CHART --values tests/charts/helloworld/values.yaml

    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
