on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      chart:
        description: "Path to the helm chart."
        required: true
        type: string

      test-command:
        description: "Command to test the chart named $CHART."
        default: ''
        type: string

      chart-registry:
        description: "URL of the chart registry."
        required: true
        type: string

      chart-registry-user:
        description: "Username for the chart registry."
        required: true
        type: string

      chart-registry-project:
        description: "Project within chart registry."
        required: true
        type: string

      chart-registry-repo:
        description: "Repo within chart registry project."
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      chart-registry-token:
        description: "Authentication token for the chart registry."
        required: true

    outputs:

      digest:
        description: "Chart version with digest."
        value: ${{ jobs.build.outputs.digest }}

      pr-tag:
        description: "Chart with pr tag."
        value: ${{ jobs.build.outputs.pr-tag }}

      pr-commit-tag:
        description: "Chart with pr and sha tag."
        value: ${{ jobs.build.outputs.pr-commit-tag }}

jobs:
  build:
    # Build the chart and push it
    uses: ./.github/workflows/build-pr-chart.yaml
    with:
      job-name: ${{ inputs.job-name }}
      chart-registry: ${{ inputs.chart-registry }}
      chart-registry-user: ${{ inputs.chart-registry-user }}
      chart-registry-project: ${{ inputs.chart-registry-project }}
      chart-registry-repo: ${{ inputs.chart-registry-repo }}
      slack-channel: ${{ inputs.slack-channel }}
      status-failure: ${{ inputs.status-failure }}
      chart: ${{ inputs.chart }}

    secrets:
      chart-registry-token: ${{ secrets.chart-registry-token }}
      slack-token: ${{ secrets.slack-token }}

  test:
    # Test the chart
    needs: build
    uses: ./.github/workflows/test-pr-chart.yaml
    if: ${{ inputs.test-command != '' }}
    with:
      job-name: ${{ inputs.job-name }}
      chart-registry: ${{ inputs.chart-registry }}
      chart-registry-user: ${{ inputs.chart-registry-user }}
      chart-registry-project: ${{ inputs.chart-registry-project }}
      chart-registry-repo: ${{ inputs.chart-registry-repo }}
      chart-registry-digest: ${{ needs.build.outputs.digest }}
      slack-channel: ${{ inputs.slack-channel }}
      status-failure: ${{ inputs.status-failure }}
      command: ${{ inputs.test-command }}

    secrets:
      chart-registry-token: ${{ secrets.chart-registry-token }}
      slack-token: ${{ secrets.slack-token }}
