name: PR Update

on:
  pull_request:

jobs:

  slack:
    # Open a new PR thread on Slack for this CI run
    uses: ./.github/workflows/slack-pr-thread.yaml
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  changes:
    # Detect which files have been changed on this PR's full history
    needs: slack
    uses: ./.github/workflows/changes.yaml
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      github-app-id: ${{ vars.APP_ID }}
      filters: |
        container-whalesay:
          - './.github/workflows/on-pr-update.yaml'
          - './.github/workflows/slack-pr-thread.yaml'
          - './.github/workflows/changes.yaml'
          - './.github/workflows/build-pr-container.yaml'
          - './.github/workflows/test-container.yaml'
          - './tests/container/**'
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  build-container-whalesay:
    # Build the whalesay container and push it as :pr-42 and :pr-42-fe45b3h
    needs:
      - slack
      - changes
    if: fromJSON(needs.changes.outputs.changes).container-whalesay == 'true'
    uses: ./.github/workflows/build-pr-container.yaml
    with:
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: whalesay
      github-app-id: ${{ vars.APP_ID }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      command: |
        docker build -t $IMAGE -f tests/container/Dockerfile tests/container
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  test-container-whalesay:
    # Test the whalesay container
    needs:
      - slack
      - build-container-whalesay
    uses: ./.github/workflows/test-container.yaml
    with:
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-digest: ${{ needs.build-container-whalesay.outputs.digest }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      command: |
        docker run $IMAGE cowsay boo
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  slack-update:
    # Update the original Slack message with the final workflow status
    # WARNING! ALL UPSTREAM JOBS MUST BE DECLARED HERE TO REPORT FAILURES CORRECTLY!
    needs:
      - slack
      - changes
      - build-container-whalesay
      - test-container-whalesay
    uses: ./.github/workflows/slack-pr-thread.yaml
    if: always()
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      slack-thread: ${{ needs.slack.outputs.thread }}
      status: ${{ contains(join(needs.*.result, ','), 'failure') && ':no_entry:' || ':white_check_mark:' }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
