on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      chart:
        description: "Path to the helm chart."
        required: true
        type: string

      test-command:
        description: "Command to test the chart named $CHART. Can be left blank but must be present in workflow file."
        required: true
        type: string

      chart-registry:
        description: "URL of the chart registry."
        required: true
        type: string

      chart-registry-user:
        description: "Username for the chart registry."
        required: true
        type: string

      chart-registry-project:
        description: "Project within chart registry."
        required: true
        type: string

      chart-registry-repo:
        description: "Repo within chart registry project."
        required: true
        type: string

      release-rules:
        description: "JSON list of rule dicts for what commit types trigger releases."
        default: |
          [
            {"type": "major", "release": "major"},
            {"type": "minor", "release": "minor"},
            {"type": "patch", "release": "patch"},
            {"type": "no-release", "release": false},

            {"type": "chore", "release": "patch"},
            {"type": "refactor", "release": "patch"},
            {"type": "style", "release": "patch"},

            {"type": "docs", "release": false},
            {"type": "test", "release": false},
            {"type": "ci", "release": false},

            {"type": "feat", "release": "minor"},

            {"type": "revert", "release": "patch"},
            {"type": "perf", "release": "patch"},
            {"type": "fix", "release": "patch"},
            {"type": "build", "release": "patch"},
          ]
        type: string

      release-branches:
        description: "JSON list of regex branch filters."
        default: |
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'main'
          ]
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        default: '${version}'
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      slack-thread:
        description: "Slack thread to reply to."
        required: true
        type: string

      status-running:
        description: "Running status for the message header."
        default: ':hammer_and_wrench:'
        type: string

      status-success:
        description: "Success status for the message header."
        default: ':white_check_mark:'
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

      github-app-id:
        description: "App ID for Github."
        required: true
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      chart-registry-token:
        description: "Authentication token for the chart registry."
        required: true

      github-app-private-key:
        description: "App private key for Github."
        required: true

    outputs:

      digest:
        description: "Chart version with digest."
        value: ${{ jobs.build.outputs.digest }}

      pr-tag:
        description: "Chart with pr tag."
        value: ${{ jobs.build.outputs.pr-tag }}

      pr-commit-tag:
        description: "Chart with pr and sha tag."
        value: ${{ jobs.build.outputs.pr-commit-tag }}

jobs:

  version:
    # Determine if a release should happen and what its version would be
    uses: ./.github/workflows/version.yaml
    with:

      job-name: ${{ inputs.job-name }}

      release-tag-format: ${{ inputs.release-tag-format}}
      release-rules: ${{ inputs.release-rules }}
      release-branches: ${{ inputs.release-branches }}

      github-app-id: ${{ inputs.github-app-id }}

      slack-channel: ${{ inputs.slack-channel }}
      slack-thread: ${{ inputs.slack-thread }}

    secrets:

      github-app-private-key: ${{ secrets.github-app-private-key }}
      slack-token: ${{ secrets.slack-token }}


  build:
    # Build the chart and push it
    needs:
      - version
    if: fromJSON(needs.version.outputs.release).new-release-published == 'true'
    uses: ./.github/workflows/build-release-chart.yaml
    with:

      job-name: ${{ inputs.job-name }}

      release-version: ${{ fromJSON(needs.version.outputs.release).release-version }}

      chart-registry: ${{ inputs.chart-registry }}
      chart-registry-user: ${{ inputs.chart-registry-user }}
      chart-registry-project: ${{ inputs.chart-registry-project }}
      chart-registry-repo: ${{ inputs.chart-registry-repo }}

      github-app-id: ${{ inputs.github-app-id }}

      slack-channel: ${{ inputs.slack-channel }}
      slack-thread: ${{ inputs.slack-thread }}
      status-running: ${{ inputs.status-running }}
      status-success: ${{ inputs.status-success }}
      status-failure: ${{ inputs.status-failure }}

      chart: ${{ inputs.chart }}

    secrets:

      chart-registry-token: ${{ secrets.chart-registry-token }}
      github-app-private-key: ${{ secrets.github-app-private-key }}
      slack-token: ${{ secrets.slack-token }}

  test:
    # Test the chart
    needs: build
    uses: ./.github/workflows/test-chart.yaml
    if: ${{ inputs.test-command != '' }}
    with:

      job-name: ${{ inputs.job-name }}

      chart-registry: ${{ inputs.chart-registry }}
      chart-registry-user: ${{ inputs.chart-registry-user }}
      chart-registry-project: ${{ inputs.chart-registry-project }}
      chart-registry-repo: ${{ inputs.chart-registry-repo }}
      chart-registry-digest: ${{ needs.build.outputs.digest }}

      github-app-id: ${{ inputs.github-app-id }}

      slack-channel: ${{ inputs.slack-channel }}
      slack-thread: ${{ inputs.slack-thread }}
      status-running: ${{ inputs.status-running }}
      status-success: ${{ inputs.status-success }}
      status-failure: ${{ inputs.status-failure }}

      command: ${{ inputs.test-command }}

    secrets:

      chart-registry-token: ${{ secrets.chart-registry-token }}
      github-app-private-key: ${{ secrets.github-app-private-key }}
      slack-token: ${{ secrets.slack-token }}

  release:
    # Release the helloworld chart re-tagging it as 1.0.0
    needs:
      - version
      - build
      - test
    uses: ./.github/workflows/release-chart.yaml
    if: ${{ ! success() && ! cancelled() && needs.build.result == 'success' }}
    with:
      job-name: ${{ inputs.job-name }}
      release-rules: ${{ needs.version.outputs.release-rules }}
      release-branches: ${{ needs.version.outputs.release-branches }}
      release-tag-format: ${{ needs.version.outputs.release-tag-format }}
      release-info: ${{ needs.version.outputs.release }}

      chart-registry: ${{ inputs.chart-registry }}
      chart-registry-user: ${{ inputs.chart-registry-user }}
      chart-registry-project: ${{ inputs.chart-registry-project }}
      chart-registry-repo: ${{ inputs.chart-registry-repo }}
      chart-registry-digest: ${{ needs.build.outputs.digest }}

      github-app-id: ${{ inputs.github-app-id }}
      slack-channel: ${{ inputs.slack-channel }}
      slack-thread: ${{ inputs.slack-thread }}

    secrets:
      chart-registry-token: ${{ secrets.chart-registry-token }}
      github-app-private-key: ${{ secrets.github-app-private-key }}
      slack-token: ${{ secrets.slack-token }}