on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      release-rules:
        description: "JSON list of rule dicts for what commit types trigger releases."
        default: |
          [
            {"type": "major", "release": "major"},
            {"type": "minor", "release": "minor"},
            {"type": "patch", "release": "patch"},
            {"type": "no-release", "release": false},

            {"type": "chore", "release": "patch"},
            {"type": "refactor", "release": "patch"},
            {"type": "style", "release": "patch"},

            {"type": "docs", "release": false},
            {"type": "test", "release": false},
            {"type": "ci", "release": false},

            {"type": "feat", "release": "minor"},

            {"type": "revert", "release": "patch"},
            {"type": "perf", "release": "patch"},
            {"type": "fix", "release": "patch"},
            {"type": "build", "release": "patch"},
          ]
        type: string

      release-branches:
        description: "JSON list of regex branch filters."
        default: |
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'main'
          ]
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        default: '${version}'
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true


jobs:
  version:
    # Determine if a release should happen and what its version would be
    uses: ./.github/workflows/version.yaml
    with:
      job-name: ${{ inputs.job-name }}
      release-tag-format: ${{ inputs.release-tag-format}}
      release-rules: ${{ inputs.release-rules }}
      release-branches: ${{ inputs.release-branches }}
      slack-channel: ${{ inputs.slack-channel }}
      status-failure: ${{ inputs.status-failure }}

    secrets:
      slack-token: ${{ secrets.slack-token }}

  release-repo:
    needs: version
    uses: ./.github/workflows/release-repo.yaml
    if: ${{ fromJSON(needs.version.outputs.release).new-release-published == 'true' }}
    with:
      job-name: ${{ inputs.job-name }}
      release-info: ${{ needs.version.outputs.release }}
      slack-channel: ${{ inputs.slack-channel }}
      status-failure: ${{ inputs.status-failure }}

    secrets:
      slack-token: ${{ secrets.slack-token }}
