#name: Release
#
#on:
#  push:
#    branches:
#      - main
#      - feat/buildx
#
#permissions:
#  # Permission needed to author a Github release
#  contents: write
#
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: false
#
#jobs:
#
#  changes:
#    # Detect which files have been changed
#    uses: ./.github/workflows/changes-release.yaml
#    with:
#      slack-channel: ${{ vars.SLACK_CHANNEL }}
#      filters: |
#        workflows:
#          - './.github/workflows/**'
#        container-whalesay:
#          - './.github/workflows/on-release.yaml'
#          - './.github/workflows/on-release-container.yaml'
#          - './.github/workflows/slack-release-thread.yaml'
#          - './.github/workflows/changes-release.yaml'
#          - './.github/workflows/version.yaml'
#          - './.github/workflows/build-release-container.yaml'
#          - './.github/workflows/test-release-container.yaml'
#          - './.github/workflows/release-container.yaml'
#          - './containers/whalesay/**'
#        container-whalesay2:
#          - './.github/workflows/on-release.yaml'
#          - './.github/workflows/on-release-container.yaml'
#          - './.github/workflows/slack-release-thread.yaml'
#          - './.github/workflows/changes-release.yaml'
#          - './.github/workflows/version.yaml'
#          - './.github/workflows/build-release-container.yaml'
#          - './.github/workflows/test-release-container.yaml'
#          - './.github/workflows/release-container.yaml'
#          - './containers/whalesay2/**'
#        chart-helloworld:
#          - './.github/workflows/on-release.yaml'
#          - './.github/workflows/on-release-chart.yaml'
#          - './.github/workflows/slack-release-thread.yaml'
#          - './.github/workflows/changes-release.yaml'
#          - './.github/workflows/version.yaml'
#          - './.github/workflows/build-release-chart.yaml'
#          - './.github/workflows/test-release-chart.yaml'
#          - './.github/workflows/release-chart.yaml'
#          - './charts/helloworld/**'
#    secrets:
#      slack-token: ${{ secrets.SLACK_TOKEN }}
#
#  container-whalesay:
#    # Build the whalesay container and push it as :rc-1.0.0
#    needs: changes
#    if: fromJSON(needs.changes.outputs.changes).container-whalesay == 'true'
#    uses: ./.github/workflows/build-and-test-release-container.yaml
#    with:
#      job-name: container-whalesay
#      registry: ${{ vars.HARBOR_REGISTRY }}
#      registry-user: ${{ vars.HARBOR_USER }}
#      registry-repo: github-workflows/whalesay
#      registry-tag-suffix: "-test"
#      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
#      release-tag-format: 'whalesay-${version}'
#      slack-channel: ${{ vars.SLACK_CHANNEL }}
#      build-file: containers/whalesay/Dockerfile
#      build-context: containers/whalesay
#      release-branches: feat/buildx
#    secrets:
#      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
#      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
#      registry-token: ${{ secrets.HARBOR_TOKEN }}
#      slack-token: ${{ secrets.SLACK_TOKEN }}
#
#  container-whalesay2:
#    # Build the whalesay2 container and push it as :rc-1.0.0
#    needs: changes
#    if: fromJSON(needs.changes.outputs.changes).container-whalesay2 == 'true'
#    uses: ./.github/workflows/build-and-test-release-container.yaml
#    with:
#      job-name: container-whalesay2
#      registry: ${{ vars.HARBOR_REGISTRY }}
#      registry-user: ${{ vars.HARBOR_USER }}
#      registry-repo: github-workflows/whalesay
#      registry-tag-suffix: "-test"
#      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
#      release-tag-format: 'whalesay2-${version}'
#      slack-channel: ${{ vars.SLACK_CHANNEL }}
#      build-file: containers/whalesay2/Dockerfile
#      build-context: containers/whalesay2
#      release-branches: feat/buildx
#    secrets:
#      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
#      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
#      registry-token: ${{ secrets.HARBOR_TOKEN }}
#      slack-token: ${{ secrets.SLACK_TOKEN }}
#
#  chart-helloworld:
#    # Build the helloworld chart and push it as x.y.z-rc
#    needs: changes
#    if: fromJSON(needs.changes.outputs.changes).chart-helloworld == 'true'
#    uses: ./.github/workflows/on-release-chart.yaml
#    with:
#      job-name: chart-helloworld
#      chart-registry: ${{ vars.HARBOR_REGISTRY }}
#      chart-registry-user: ${{ vars.HARBOR_USER }}
#      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
#      chart-registry-repo: helloworld
#      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
#      release-tag-format: 'helloworld-${version}'
#      slack-channel: ${{ vars.SLACK_CHANNEL }}
#      chart: charts/helloworld
#    secrets:
#      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
#      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
#      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
#      slack-token: ${{ secrets.SLACK_TOKEN }}
#
##  workflows:
##    # Release the workflows repo
##    needs:
##      - changes
##      - container-whalesay
##      - container-whalesay2
##      - chart-helloworld
##    if:  ${{ always() && (!contains(join(needs.*.result, ','), 'failure') && !contains(join(needs.*.result, ','), 'cancelled') && fromJSON(needs.changes.outputs.changes).workflows == 'true') }}
##
##    uses: ./.github/workflows/on-release-repo.yaml
##    with:
##      job-name: workflows
##      release-tag-format: 'v${version}'
##      slack-channel: ${{ vars.SLACK_CHANNEL }}
##    secrets:
##      slack-token: ${{ secrets.SLACK_TOKEN }}
