name: Release

on:
  push:
    branches:
      - main

permissions:
  # Permission needed to author a Github release 
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  changes:
    # Detect which files have been changed
    uses: ./.github/workflows/changes-release.yaml
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      filters: |
        workflows:
          - './.github/workflows/**'
        container-whalesay:
          - './.github/workflows/on-release.yaml'
          - './.github/workflows/on-release-container.yaml'
          - './.github/workflows/slack-release-thread.yaml'
          - './.github/workflows/changes-release.yaml'
          - './.github/workflows/version.yaml'
          - './.github/workflows/build-release-container.yaml'
          - './.github/workflows/test-release-container.yaml'
          - './.github/workflows/release-container.yaml'
          - './containers/whalesay/**'
        container-whalesay2:
          - './.github/workflows/on-release.yaml'
          - './.github/workflows/on-release-container.yaml'
          - './.github/workflows/slack-release-thread.yaml'
          - './.github/workflows/changes-release.yaml'
          - './.github/workflows/version.yaml'
          - './.github/workflows/build-release-container.yaml'
          - './.github/workflows/test-release-container.yaml'
          - './.github/workflows/release-container.yaml'
          - './containers/whalesay2/**'
        chart-helloworld:
          - './.github/workflows/on-release.yaml'
          - './.github/workflows/on-release-chart.yaml'
          - './.github/workflows/slack-release-thread.yaml'
          - './.github/workflows/changes-release.yaml'
          - './.github/workflows/version.yaml'
          - './.github/workflows/build-release-chart.yaml'
          - './.github/workflows/test-release-chart.yaml'
          - './.github/workflows/release-chart.yaml'
          - './charts/helloworld/**'
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  container-whalesay:
    # Build the whalesay container and push it as :rc-1.0.0
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).container-whalesay == 'true'
    uses: ./.github/workflows/on-release-container.yaml
    with:
      job-name: container-whalesay
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: whalesay
      release-tag-format: 'whalesay-${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-command: |
        docker build -t $IMAGE -f containers/whalesay/Dockerfile containers/whalesay
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  container-whalesay2:
    # Build the whalesay2 container and push it as :rc-1.0.0
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).container-whalesay2 == 'true'
    uses: ./.github/workflows/on-release-container.yaml
    with:
      job-name: container-whalesay2
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: whalesay2
      release-tag-format: 'whalesay2-${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-command: |
        docker build -t $IMAGE -f containers/whalesay2/Dockerfile containers/whalesay2
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  chart-helloworld:
    # Build the helloworld chart and push it as x.y.z-rc
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).chart-helloworld == 'true'
    uses: ./.github/workflows/on-release-chart.yaml
    with:
      job-name: chart-helloworld
      chart-registry: ${{ vars.HARBOR_REGISTRY }}
      chart-registry-user: ${{ vars.HARBOR_USER }}
      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
      chart-registry-repo: helloworld
      release-tag-format: 'helloworld-${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      chart: charts/helloworld
    secrets:
      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  workflows:
    # Release the workflows repo
    needs:
      - changes
      - container-whalesay
      - container-whalesay2
      - chart-helloworld
    if:  ${{ always() && (!contains(join(needs.*.result, ','), 'failure') && !contains(join(needs.*.result, ','), 'cancelled') && fromJSON(needs.changes.outputs.changes).workflows == 'true') }}

    uses: ./.github/workflows/on-release-repo.yaml
    with:
      job-name: workflows
      release-tag-format: 'v${version}'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
