on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      build-file:
        description: "Path to the container file."
        required: true
        type: string

      build-context:
        description: "Path to the build root dir."
        default: '.'
        type: string

      test-flags:
        description: "Arguments passed to docker run."
        default: ''
        type: string

      test-args:
        description: "Arguments passed to the container."
        default: ''
        type: string

      registry:
        description: "URL of the container registry."
        required: true
        type: string

      registry-user:
        description: "Username for the container registry."
        required: true
        type: string

      registry-repo:
        description: "Repo within container registry project."
        required: true
        type: string

      registry-tag-prefix:
        description: "Prefix to use when tagging container"
        default: ''
        type: string

      registry-tag-suffix:
        description: "Suffix to use when tagging container"
        default: ''
        type: string

      release-rules:
        description: "JSON list of rule dicts for what commit types trigger releases."
        default: |
          [
            {"type": "major", "release": "major"},
            {"type": "minor", "release": "minor"},
            {"type": "patch", "release": "patch"},
            {"type": "no-release", "release": false},

            {"type": "chore", "release": "patch"},
            {"type": "refactor", "release": "patch"},
            {"type": "style", "release": "patch"},

            {"type": "docs", "release": false},
            {"type": "test", "release": false},
            {"type": "ci", "release": false},

            {"type": "feat", "release": "minor"},

            {"type": "revert", "release": "patch"},
            {"type": "perf", "release": "patch"},
            {"type": "fix", "release": "patch"},
            {"type": "build", "release": "patch"},
          ]
        type: string

      release-branches:
        description: "JSON list of regex branch filters."
        default: |
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'main'
          ]
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        default: '${version}'
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

      cosign-public-key:
        description: "Public key for cosigning images."
        required: false
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      registry-token:
        description: "Authentication token for the container registry."
        required: true

      cosign-private-key:
        description: "Private key for cosigning images."
        required: false

      cosign-password:
        description: "Private key password for cosigning images."
        required: false

jobs:
  container:
    runs-on:
      labels: [ self-hosted, linux, x64 ]
      group: heavy
    steps:
      - name: get workflow reference
        id: workflows-ref
        run: |
          sha=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r '.referenced_workflows[0] | .sha')
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: clone repo
        uses: actions/checkout@v4

      - name: clone actions from workflows repo
        uses: actions/checkout@v4
        with:
          repository: SwanseaUniversityMedical/workflows
          ref: ${{ steps.workflows-ref.outputs.sha }}
          path: .tmp
          sparse-checkout: |
            .github/actions/pr-container
            .github/actions/release-container

      - name: pr
        if: github.event_name == 'pull_request'
        uses: ./.tmp/.github/actions/pr-container
        with:
          job-name: ${{ inputs.job-name }}
          registry: ${{ inputs.registry }}
          registry-user: ${{ inputs.registry-user }}
          registry-repo: ${{ inputs.registry-repo }}
          cosign-public-key: ${{ inputs.cosign-public-key }}
          slack-channel: ${{ inputs.slack-channel }}
          build-file: ${{ inputs.build-file }}
          build-context: ${{ inputs.build-context }}
          test-flags: ${{ inputs.test-flags }}
          test-args: ${{ inputs.test-args }}
          cosign-private-key: ${{ secrets.cosign-private-key }}
          cosign-password: ${{ secrets.cosign-password }}
          registry-token: ${{ secrets.registry-token }}
          slack-token: ${{ secrets.slack-token }}

      - name: release
        if: github.event_name == 'push'
        uses: ./.tmp/.github/actions/release-container
        with:
          job-name: ${{ inputs.job-name }}
          registry: ${{ inputs.registry }}
          registry-user: ${{ inputs.registry-user }}
          registry-repo: ${{ inputs.registry-repo }}
          cosign-public-key: ${{ inputs.cosign-public-key }}
          slack-channel: ${{ inputs.slack-channel }}
          build-file: ${{ inputs.build-file }}
          build-context: ${{ inputs.build-context }}
          test-flags: ${{ inputs.test-flags }}
          test-args: ${{ inputs.test-args }}
          cosign-private-key: ${{ secrets.cosign-private-key }}
          cosign-password: ${{ secrets.cosign-password }}
          registry-token: ${{ secrets.registry-token }}
          slack-token: ${{ secrets.slack-token }}
          release-branches: ${{ inputs.release-branches }}
          release-rules: ${{ inputs.release-rules }}
          registry-tag-prefix: ${{ inputs.registry-tag-prefix }}
          registry-tag-suffix: ${{ inputs.registry-tag-suffix }}
          release-tag-format: ${{ inputs.release-tag-format }}