on:
  workflow_call:
    inputs:

      job-name:
        description: "Name of the release asset."
        required: true
        type: string

      comment-release:
        description: "Release comment creation and update."
        default: "true"
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        default: '${version}'
        type: string

    outputs:
      release-info:
        description: "All release info in one json blob."
        value: ${{ jobs.repo.outputs.release-info }}

      new-release-published:
        description: "Semantic release output."
        value: ${{ jobs.repo.outputs.new-release-published }}

      release-version:
        description: "Semantic release output."
        value: ${{ jobs.repo.outputs.release-version }}

      git-tag:
        description: "Semantic release output."
        value: ${{ jobs.repo.outputs.git-tag }}

      pr-number:
        description: "Release PR number."
        value: ${{ jobs.repo.outputs.pr-number }}

jobs:
  repo:
    runs-on:
      labels: [ self-hosted, linux, x64 ]
      group: heavy
    outputs:
      release-info: ${{ steps.release.outputs.release-info }}
      new-release-published: ${{ steps.release.outputs.new-release-published }}
      release-version: ${{ steps.release.outputs.release-version }}
      git-tag: ${{ steps.release.outputs.git-tag }}
      pr-number: ${{ steps.release.outputs.pr-number }}
    steps:
      - id: release
        uses: SwanseaUniversityMedical/workflows/.github/actions/pr-and-release-repo@fix/determine-bump
        with:
          name: ${{ inputs.job-name }}
          release-tag-format: ${{ inputs.release-tag-format }}
          comment-release: ${{ inputs.comment-release }}
