on:
  workflow_call:
    inputs:

      job-name:
        description: "Name of the release asset."
        required: true
        type: string

      major-colour:
        description: "Colour for the major release label."
        default: 'B60205'
        type: string

      minor-colour:
        description: "Colour for the minor release label."
        default: '8BD931'
        type: string

      patch-colour:
        description: "Colour for the patch release label."
        default: 'FBCA04'
        type: string

      chart:
        description: "Path to the helm chart."
        required: true
        type: string

      comment-pr:
        description: "PR comment creation and update."
        default: "false"
        type: string

      comment-release:
        description: "Release comment creation and update."
        default: "true"
        type: string

      test-command:
        description: "Command to test the chart named $CHART."
        default: ''
        type: string

      registry:
        description: "URL of the chart registry."
        required: true
        type: string

      registry-user:
        description: "Username for the chart registry."
        required: true
        type: string

      registry-project:
        description: "Project within chart registry."
        required: true
        type: string

      registry-repo:
        description: "Repo within chart registry project."
        required: true
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        default: '${version}'
        type: string

      cosign-public-key:
        description: "Public key for cosigning images."
        required: false
        type: string

    secrets:

      registry-token:
        description: "Authentication token for the chart registry."
        required: true

      cosign-private-key:
        description: "Private key for cosigning charts."
        required: false

      cosign-password:
        description: "Private key password for cosigning charts."
        required: false

jobs:
  chart:
    runs-on:
      labels: [ self-hosted, linux, x64 ]
      group: heavy
    steps:
      - uses: SwanseaUniversityMedical/workflows/.github/actions/pr-and-release-chart@v1.0.0-pr-and-release-chart-action
        with:
          name: ${{ inputs.job-name }}
          major-colour: ${{ inputs.major-colour }}
          minor-colour: ${{ inputs.minor-colour }}
          patch-colour: ${{ inputs.patch-colour }}
          comment-pr: ${{ inputs.comment-pr }}
          comment-release: ${{ inputs.comment-release }}
          registry: ${{ inputs.registry }}
          registry-user: ${{ inputs.registry-user }}
          registry-project: ${{ inputs.registry-project }}
          registry-repo: ${{ inputs.registry-repo }}
          cosign-public-key: ${{ inputs.cosign-public-key }}
          chart: ${{ inputs.chart }}
          test-command: ${{ inputs.test-command }}
          release-tag-format: ${{ inputs.release-tag-format }}
          cosign-private-key: ${{ secrets.cosign-private-key }}
          cosign-password: ${{ secrets.cosign-password }}
          registry-token: ${{ secrets.registry-token }}
