on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      chart:
        description: "Path to the helm chart."
        required: true
        type: string

      comment-enabled:
        description: "PR comment creation and update."
        default: "false"
        type: string

      test-command:
        description: "Command to test the chart named $CHART."
        default: ''
        type: string

      registry:
        description: "URL of the chart registry."
        required: true
        type: string

      registry-user:
        description: "Username for the chart registry."
        required: true
        type: string

      registry-project:
        description: "Project within chart registry."
        required: true
        type: string

      registry-repo:
        description: "Repo within chart registry project."
        required: true
        type: string

      tag-suffix:
        description: "Suffix to use when tagging chart"
        default: ''
        type: string

      release-rules:
        description: "JSON list of rule dicts for what commit types trigger releases."
        default: |
          [
            {"type": "major", "release": "major"},
            {"type": "minor", "release": "minor"},
            {"type": "patch", "release": "patch"},
            {"type": "no-release", "release": false},

            {"type": "chore", "release": "patch"},
            {"type": "refactor", "release": "patch"},
            {"type": "style", "release": "patch"},

            {"type": "docs", "release": false},
            {"type": "test", "release": false},
            {"type": "ci", "release": false},

            {"type": "feat", "release": "minor"},

            {"type": "revert", "release": "patch"},
            {"type": "perf", "release": "patch"},
            {"type": "fix", "release": "patch"},
            {"type": "build", "release": "patch"},
          ]
        type: string

      release-branches:
        description: "JSON list of regex branch filters."
        default: |
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'main'
          ]
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        default: '${version}'
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      cosign-public-key:
        description: "Public key for cosigning images."
        required: false
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      registry-token:
        description: "Authentication token for the chart registry."
        required: true

      cosign-private-key:
        description: "Private key for cosigning charts."
        required: false

      cosign-password:
        description: "Private key password for cosigning charts."
        required: false

jobs:
  chart:
    runs-on:
      labels: [ self-hosted, linux, x64 ]
      group: heavy
    steps:
      - name: add release labels to repo
        uses: actions/github-script@v7.0.1
        with:
          script: |
            var inputs = ${{ toJSON(inputs) }};
            var asset_name = inputs['job-name'].trim();

            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "major-release-" + asset_name,
              color: "B60205"
            });

            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "minor-release-" + asset_name,
              color: "8BD931"
            });

            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "patch-release-" + asset_name,
              color: "FBCA04"
            });

      - name: get workflow reference
        id: workflows-ref
        run: |
          sha=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r '.referenced_workflows[0] | .sha')
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: clone repo
        uses: actions/checkout@v4

      - name: clone actions from workflows repo
        uses: actions/checkout@v4
        with:
          repository: SwanseaUniversityMedical/workflows
          ref: ${{ steps.workflows-ref.outputs.sha }}
          path: .tmp
          sparse-checkout: |
            .github/actions/pr-chart
            .github/actions/release-chart

      - name: pr
        if: github.event_name == 'pull_request'
        uses: ./.tmp/.github/actions/pr-chart
        with:
          job-name: ${{ inputs.job-name }}
          comment-enabled: ${{ inputs.comment-enabled }}
          registry: ${{ inputs.registry }}
          registry-user: ${{ inputs.registry-user }}
          registry-project: ${{ inputs.registry-project }}
          registry-repo: ${{ inputs.registry-repo }}
          cosign-public-key: ${{ inputs.cosign-public-key }}
          slack-channel: ${{ inputs.slack-channel }}
          chart: ${{ inputs.chart }}
          test-command: ${{ inputs.test-command }}
          cosign-private-key: ${{ secrets.cosign-private-key }}
          cosign-password: ${{ secrets.cosign-password }}
          registry-token: ${{ secrets.registry-token }}
          slack-token: ${{ secrets.slack-token }}

      - name: release
        if: github.event_name == 'push'
        uses: ./.tmp/.github/actions/release-chart
        with:
          job-name: ${{ inputs.job-name }}
          registry: ${{ inputs.registry }}
          registry-user: ${{ inputs.registry-user }}
          registry-project: ${{ inputs.registry-project }}
          registry-repo: ${{ inputs.registry-repo }}
          cosign-public-key: ${{ inputs.cosign-public-key }}
          slack-channel: ${{ inputs.slack-channel }}
          chart: ${{ inputs.chart }}
          test-command: ${{ inputs.test-command }}
          release-branches: ${{ inputs.release-branches }}
          release-rules: ${{ inputs.release-rules }}
          tag-suffix: ${{ inputs.tag-suffix }}
          release-tag-format: ${{ inputs.release-tag-format }}
          cosign-private-key: ${{ secrets.cosign-private-key }}
          cosign-password: ${{ secrets.cosign-password }}
          registry-token: ${{ secrets.registry-token }}
          slack-token: ${{ secrets.slack-token }}