on:
  workflow_call:
    inputs:

      runs-on:
        description: "Name of the runner group to execute on."
        default: "ubuntu-latest"
        type: string

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      comment-release:
        description: "Release comment creation and update."
        default: "true"
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        default: '${version}'
        type: string

      major-colour:
        description: "Colour for the major release label."
        default: 'B60205'
        type: string

      minor-colour:
        description: "Colour for the minor release label."
        default: '8BD931'
        type: string

      patch-colour:
        description: "Colour for the patch release label."
        default: 'FBCA04'
        type: string

    outputs:
      release-info:
        description: "All release info in one json blob."
        value: ${{ jobs.repo.outputs.release-info }}

      new-release-published:
        description: "Semantic release output."
        value: ${{ jobs.repo.outputs.new-release-published }}

      release-version:
        description: "Semantic release output."
        value: ${{ jobs.repo.outputs.release-version }}

      git-tag:
        description: "Semantic release output."
        value: ${{ jobs.repo.outputs.git-tag }}

      pr-number:
        description: "Release PR number."
        value: ${{ jobs.repo.outputs.pr-number }}

jobs:
  repo:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      release-info: ${{ steps.release.outputs.release-info }}
      new-release-published: ${{ steps.release.outputs.new-release-published }}
      release-version: ${{ steps.release.outputs.release-version }}
      git-tag: ${{ steps.release.outputs.git-tag }}
      pr-number: ${{ steps.release.outputs.pr-number }}
    steps:
      - name: get workflow reference
        id: workflows-ref
        run: |
          sha=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r '.referenced_workflows[0] | .sha')
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: clone repo
        uses: actions/checkout@v4

      - name: clone actions from workflows repo
        uses: actions/checkout@v4
        with:
          repository: SwanseaUniversityMedical/workflows
          ref: ${{ steps.workflows-ref.outputs.sha }}
          path: .tmp
          sparse-checkout: |
            .github/actions/release-repo
            .github/actions/release-create-labels
            .github/actions/release-determine-bump

      - name: create release labels
        id: create-release-labels
        uses: ./.tmp/.github/actions/release-create-labels
        with:
          job-name: ${{ inputs.job-name }}
          major-colour: ${{ inputs.major-colour }}
          minor-colour: ${{ inputs.minor-colour }}
          patch-colour: ${{ inputs.patch-colour }}

      - name: release
        id: release
        if: github.event_name == 'push'
        uses: ./.tmp/.github/actions/release-repo
        with:
          job-name: ${{ inputs.job-name }}
          release-tag-format: ${{ inputs.release-tag-format }}
          major-label: ${{ steps.create-release-labels.outputs.major }}
          minor-label: ${{ steps.create-release-labels.outputs.minor }}
          patch-label: ${{ steps.create-release-labels.outputs.patch }}
