on:
  workflow_call:
    inputs:

      runs-on:
        description: "Name of the runner group to execute on."
        default: "ubuntu-latest"
        type: string

      config:
        description: "Path to the labeler config file within the repo."
        default: ".github/labeler.yaml"
        type: string

jobs:
  label:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: clone config from repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.config }}

      - name: apply labels to pr
        uses: actions/labeler@v5
        with:
          configuration-path: ${{ inputs.config }}
