on:
  workflow_call:
    inputs:

      config:
        description: "Path to the labeler config file within the repo."
        default: ".github/labeler.yaml"
        type: string

jobs:
  lint:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: light
    steps:
      - name: clone config from repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.config }}

      - name: apply labels to pr
        uses: actions/labeler@v5
        with:
          configuration-path: ${{ inputs.config }}
