on:
  workflow_call:
    inputs:

      error-label:
        description: "Label to add on bad lints."
        default: "BAD PR TITLE"
        type: string

      config:
        description: "Path to the commitlint config file within the repo."
        default: ".github/commitlint.config.mjs"
        type: string

jobs:
  lint:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: light
    steps:
      - name: clone config from repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.config }}

      - name: cache node modules
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ github.workflow }}-commitlint

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install commitlint
        shell: bash
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli

      - name: lint pr title
        id: commitlint
        shell: bash
        run: |
          echo "$TITLE" | npx commitlint --config="$CONFIG"
        env:
          TITLE: ${{ github.event.pull_request.title }}
          CONFIG: ${{ inputs.config }}

      - name: Add error label on bad lint
        uses: actions/github-script@v7.0.1
        if: failure()
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["${{ inputs.error-label }}"]
            })

      - name: Remove error label on successful lint
        uses: actions/github-script@v7.0.1
        if: success()
        continue-on-error: true
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "${{ inputs.error-label }}"
            });
