on:
  workflow_call:
    inputs:

      error-label:
        description: "Label to add on bad lints."
        default: ":black_nib: Bad PR Title"
        type: string

      comment-header:
        description: "Header line for the PR comment."
        default: ":black_nib: PR Title Commitlint"
        type: string

      comment-success:
        description: "Success message for the PR comment."
        default: ":heavy_check_mark: Lint success!"
        type: string

      comment-error:
        description: "Error message for the PR comment."
        default: ":x: Lint error! Fix title before merging!"
        type: string

      config:
        description: "Path to the commitlint config file within the repo."
        default: ".github/commitlint.config.mjs"
        type: string

jobs:
  pr-lint:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: light
    steps:
      - uses: SwanseaUniversityMedical/workflows/.github/actions/pr-lint@v1.0.2-pr-lint-action
        with:
          error-label: ${{ inputs.error-label }}
          comment-header: ${{ inputs.comment-header }}
          comment-success: ${{ inputs.comment-success }}
          comment-error: ${{ inputs.comment-error }}
          config: ${{ inputs.config }}
