name: build, push, test

on:
  pull_request:

env:
  WHALESAY_IMAGE: ${{ vars.HARBOR_REGISTRY }}/${{ vars.HARBOR_PROJECT }}/whalesay

jobs:

  changes:
    runs-on: [self-hosted, linux, x64]

    outputs:
      container-whalesay: ${{ steps.changes.outputs.container-whalesay }}

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: detect changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ steps.generate-token.outputs.token }}
          filters: |
            container-whalesay:
              - './.github/workflows/pr.yaml'
              - './tests/container/**'

  build-container-whalesay:
    needs: changes
    if: needs.changes.outputs.container-whalesay == 'true'

    runs-on: [self-hosted, linux, x64]

    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      digest: ${{ steps.build.outputs.digest }}
      image: ${{ env.WHALESAY_IMAGE }}@${{ steps.build.outputs.digest }}

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: install QEMU
        uses: docker/setup-qemu-action@v2

      - name: install docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."${{ vars.HARBOR_REGISTRY }}"]
              insecure = true

      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_REGISTRY }}
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: container metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.WHALESAY_IMAGE }}
          tags: |
            type=ref,event=pr,prefix=pr-,suffix=-{{sha}}
            type=ref,event=pr,prefix=pr-,suffix=

      - name: build and push container
        uses: docker/build-push-action@v4
        id: build
        with:
          context: tests/container
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: comment the image tags to the pr
        uses: actions/github-script@v6
        with:
          script: |
            
            var tags = steps.meta.outputs.tags.map(
              (tag) => ('docker pull {0}'.format(tag))
            ).join('\n');
            var digest = 'docker pull {0}@{1}'.format(env.WHALESAY_IMAGE, steps.build.outputs.digest);
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '```\n{tags}\n\n{digest}\n```\n\n:robot: :whale2: :package: :passenger_ship:\n'
            })

  test-container-whalesay:
    needs: build-container-whalesay

    runs-on: [self-hosted, linux, x64]

    steps:
      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_REGISTRY }}
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: pull container
        run: |
          docker pull ${{ needs.build-container-whalesay.outputs.image }}

      - name: test container
        run: |
          docker run \
            ${{ needs.build-container-whalesay.outputs.image }} \
              cowsay boo
