name: Release Commit Lint PR Title

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pr-title-commitlint.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pr-title-commitlint:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: pr-title-commitlint
      comment-release: true
      release-tag-format: 'v${version}-pr-title-commitlint'
