name: Release PR Labeler

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pr-labeler.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-pr-labeler:
    uses: ./.github/workflows/on-release-repo.yaml
    with:
      job-name: release-pr-labeler
      release-tag-format: 'v${version}-pr-labeler'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
