on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      release-rules:
        description: "JSON list of rule dicts for what commit types trigger releases."
        required: true
        type: string

      release-branches:
        description: "JSON list of regex branch filters."
        required: true
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        required: true
        type: string

      release-info:
        description: "JSON list of release info from dry run."
        required: true
        type: string
        
      container-registry:
        description: "URL of the container registry."
        required: true
        type: string

      container-registry-user:
        description: "Username for the container registry."
        required: true
        type: string

      container-registry-project:
        description: "Project within container registry."
        required: true
        type: string

      container-registry-repo:
        description: "Repo within container registry project."
        required: true
        type: string

      container-registry-digest:
        description: "URI of the container."
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      slack-thread:
        description: "Slack thread to reply to."
        required: true
        type: string

      status-running:
        description: "Running status for the message header."
        default: ':hammer_and_wrench:'
        type: string

      status-success:
        description: "Success status for the message header."
        default: ':white_check_mark:'
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

      github-app-id:
        description: "App ID for Github."
        required: true
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true
        
      container-registry-token:
        description: "Authentication token for the container registry."
        required: true

      github-app-private-key:
        description: "App private key for Github."
        required: true

    outputs:

      release:
        description: "JSON encoded dictionary of release parameters."
        value: ${{ jobs.release.outputs.release }}

jobs:
  release-container:
    runs-on: [self-hosted, linux, x64]

    outputs:
      release: ${{ toJSON(steps.release.outputs) }}

    steps:
      - name: update slack thread
        uses: archive/github-actions-slack@v2.7.0
        id: slack
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-optional-thread_ts: ${{ inputs.slack-thread }}
          slack-text: |
            ${{ inputs.status-running }}  job: ${{ github.job }} / ${{ inputs.job-name }}

      - name: clone repo
        uses: actions/checkout@v3

      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ inputs.github-app-id }}
          private_key: ${{ secrets.github-app-private-key }}

#      - name: Set up mutex
#        uses: ben-z/gh-action-mutex@v1.0-alpha-7
#        with:
#          branch: release/mutex

      - name: release
        uses: actions/github-script@v6
        id: release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          RELEASE_NOTES: |
            ${{ fromJSON(inputs.release-info).release-notes }}
        with:
          retries: 3
          script: |
            github.rest.repos.createRelease({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              tag_name: "${{ fromJSON(inputs.release-info).git-tag }}",
              target_commitish: "${{ github.sha }}",
              body: process.env.RELEASE_NOTES,
              name: "${{ fromJSON(inputs.release-info).git-tag }}"
            });
            
      - name: build image uri
        run: |
          echo "IMAGE=${{ inputs.container-registry }}/${{ inputs.container-registry-project }}/${{ inputs.container-registry-repo }}" >> $GITHUB_ENV

      - name: create tag
        run: |
          echo "RELEASE_TAG=${{ env.IMAGE }}:${{ fromJSON(inputs.release-info).release-version }}" >> $GITHUB_ENV 

      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.container-registry }}
          username: ${{ inputs.container-registry-user }}
          password: ${{ secrets.container-registry-token }}

      - name: pull container
        run: |
          docker pull ${{ inputs.container-registry-digest }}

      - name: tag container
        run: |
          docker tag ${{ inputs.container-registry-digest }} ${{ env.RELEASE_TAG }}

      - name: push container
        run: |
          docker push ${{ env.RELEASE_TAG }}

      - name: update slack thread success
        uses: archive/github-actions-slack@v2.7.0
        if: success()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-function: update-message
          slack-update-message-ts: ${{ fromJson(steps.slack.outputs.slack-result).response.message.ts }}
          slack-update-message-text: |
            ${{ inputs.status-success }}  job: ${{ github.job }} / ${{ inputs.job-name }}
            
            ```
            Status: Released new version!
            Version: ${{ steps.release.outputs.release-version }}
            
            docker pull ${{ env.RELEASE_TAG }}
            ```

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        if: failure()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-function: update-message
          slack-update-message-ts: ${{ fromJson(steps.slack.outputs.slack-result).response.message.ts }}
          slack-update-message-text: |
            ${{ inputs.status-failure }}  job: ${{ github.job }} / ${{ inputs.job-name }}
