name: Release Commit Lint PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/pr-title-commitlint.yaml'

      - '.github/workflows/pr-and-release-repo.yaml'
      - '.github/actions/release-create-labels/action.yaml'
      - '.github/actions/release-determine-bump/action.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pr-title-commitlint.yaml'

      - '.github/workflows/pr-and-release-repo.yaml'
      - '.github/actions/release-create-labels/action.yaml'
      - '.github/actions/release-determine-bump/action.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-pr-title-commitlint:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: release-pr-title-commitlint
      comment-release: true
      release-tag-format: 'v${version}-pr-title-commitlint'
