name: Release Commit Lint PR Title

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/commitlint.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-pr-title-commitlint:
    uses: ./.github/workflows/on-release-repo.yaml
    with:
      job-name: release-pr-title-commitlint
      release-tag-format: 'v${version}-pr-title-commitlint'
      slack-channel: ${{ vars.SLACK_CHANNEL }}
    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}
