name: Release Bulk Container Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/release-bulk-containers-workflow.yaml'

      - '.github/workflows/bulk-pr-and-release-container.yaml'
      - '.github/actions/pr-container/action.yaml'
      - '.github/actions/bulk-release-container/action.yaml'

      - '.github/workflows/pr-and-release-repo.yaml'
      - '.github/actions/release-repo/action.yaml'
      - '.github/actions/release-create-labels/action.yaml'
      - '.github/actions/release-determine-bump/action.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release-bulk-containers-workflow.yaml'

      - '.github/workflows/bulk-pr-and-release-container.yaml'
      - '.github/actions/pr-container/action.yaml'
      - '.github/actions/bulk-release-container/action.yaml'

      - '.github/workflows/pr-and-release-repo.yaml'
      - '.github/actions/release-repo/action.yaml'
      - '.github/actions/release-create-labels/action.yaml'
      - '.github/actions/release-determine-bump/action.yaml'


permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  bulk-containers:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      runs-on: "ubuntu-latest"
      job-name: bulk-containers
      comment-release: true
      release-tag-format: 'v${version}-bulk-containers'
