on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      release-info:
        description: "JSON list of release info from dry run."
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

    outputs:

      release:
        description: "JSON encoded dictionary of release parameters."
        value: ${{ jobs.release-repo.outputs.release }}

jobs:
  release-repo:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: heavy

    outputs:
      release: ${{ toJSON(steps.release.outputs) }}

    steps:
      - name: release
        uses: actions/github-script@v7
        id: release
        env:
          RELEASE_NOTES: |
            ${{ fromJSON(inputs.release-info).release-notes }}
        with:
          retries: 3
          github-token: ${{ github.token }}
          script: |
            github.rest.repos.createRelease({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              tag_name: "${{ fromJSON(inputs.release-info).git-tag }}",
              target_commitish: "${{ github.sha }}",
              body: process.env.RELEASE_NOTES,
              name: "${{ fromJSON(inputs.release-info).git-tag }}"
            });

      - name: annotate the ci run with container tags
        run: >-
          echo "::notice title=Job: ${{ github.job }} / ${{ inputs.job-name }}::%0A
          Created new release version ${{ fromJSON(inputs.release-info).release-version }}!"

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        if: failure()
        continue-on-error: true
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            *${{ github.repository }}*\n
            *Release ${{ github.ref }}*\n
            ${{ inputs.status-failure }} job: ${{ github.job }} / ${{ inputs.job-name }}\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>\n
            ```
            Ref:      ${{ github.ref }}\n
            Sha:      ${{ github.sha }}\n
            Workflow: ${{ github.workflow }}\n
            Run:      ${{ github.run_id }}
            ```
