name: Release PR Labeler

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pr-labeler.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pr-labeler:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: pr-labeler
      comment-release: true
      release-tag-format: 'v${version}-pr-labeler'
