name: Release Renovate Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/release-renovate-workflow.yaml'

      - '.github/actions/renovate/**'

      - '.github/workflows/pr-and-release-repo.yaml'
      - '.github/actions/release-repo/action.yaml'
      - '.github/actions/release-create-labels/action.yaml'
      - '.github/actions/release-determine-bump/action.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release-renovate-workflow.yaml'

      - '.github/actions/renovate/**'

      - '.github/workflows/pr-and-release-repo.yaml'
      - '.github/actions/release-repo/action.yaml'
      - '.github/actions/release-create-labels/action.yaml'
      - '.github/actions/release-determine-bump/action.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  release-renovate-workflow:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      runs-on: "feda-linux-default"
      job-name: renovate
      comment-release: true
      release-tag-format: 'v${version}-renovate'
