on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      release-info:
        description: "JSON list of release info from dry run."
        required: true
        type: string
        
      registry:
        description: "URL of the container registry."
        required: true
        type: string

      registry-user:
        description: "Username for the container registry."
        required: true
        type: string

      registry-repo:
        description: "Repo within container registry project."
        required: true
        type: string

      registry-digest:
        description: "URI of the container."
        required: true
        type: string

      registry-tag-prefix:
        description: "Prefix to use when tagging container"
        required: true
        type: string

      registry-tag-suffix:
        description: "Suffix to use when tagging container"
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

      cosign-public-key:
        description: "Public key for cosigning images."
        required: false
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true
        
      registry-token:
        description: "Authentication token for the container registry."
        required: true

      cosign-private-key:
        description: "Private key for cosigning images."
        required: false

      cosign-password:
        description: "Private key password for cosigning images."
        required: false

    outputs:

      release:
        description: "JSON encoded dictionary of release parameters."
        value: ${{ jobs.release-container.outputs.release }}

jobs:
  release-container:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: heavy

    outputs:
      release: ${{ toJSON(steps.release.outputs) }}

    steps:
      - name: build image uri
        run: |
          echo "IMAGE=${{ inputs.registry }}/${{ inputs.registry-repo }}" >> $GITHUB_ENV

      - name: create tag
        run: |
          echo "RELEASE_TAG=${{ env.IMAGE }}:${{ inputs.registry-tag-prefix }}${{ fromJSON(inputs.release-info).release-version }}${{ inputs.registry-tag-suffix }}" >> $GITHUB_ENV 

      - name: install cosign
        if: inputs.cosign-public-key != ''
        uses: sigstore/cosign-installer@v3.1.2

      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-user }}
          password: ${{ secrets.registry-token }}

      - name: forward proxy settings
        run: |
          echo "HTTP_PROXY=$HTTP_PROXY" >> $GITHUB_ENV
          echo "HTTPS_PROXY=$HTTPS_PROXY" >> $GITHUB_ENV
          echo "NO_PROXY=$NO_PROXY" >> $GITHUB_ENV

      - name: install buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            env.http_proxy=${{ env.HTTP_PROXY }}
            env.https_proxy=${{ env.HTTPS_PROXY }}
            "env.no_proxy='${{ env.NO_PROXY }}'"

      - name: cosign verify container
        if: inputs.cosign-public-key != ''
        env:
          COSIGN_PUBLIC_KEY: ${{ inputs.cosign-public-key }}
          TAG: ${{ inputs.registry }}/${{ inputs.registry-repo }}
          DIGEST: ${{ inputs.registry-digest }}
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY "${TAG}@${DIGEST}"

      - name: container metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ inputs.registry }}/${{ inputs.registry-repo }}
          tags: |
            type=raw,value=${{ inputs.registry-tag-prefix }}${{ inputs.release-version }}${{ inputs.registry-tag-suffix }}

      - name: retag container
        run: docker buildx imagetools create -t ${{ inputs.registry }}/${{ inputs.registry-repo }}:${{ steps.meta.outputs.tags }} ${{ inputs.registry }}/${{ inputs.registry-repo }}@${{ inputs.registry-digest }}

      - name: cosign image with key
        if: inputs.cosign-public-key != ''
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.cosign-private-key }}
          COSIGN_PASSWORD: ${{ secrets.cosign-password }}
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ inputs.registry-digest }}

      - name: cosign verify container
        if: inputs.cosign-public-key != ''
        env:
          COSIGN_PUBLIC_KEY: ${{ inputs.cosign-public-key }}
          TAG: ${{ inputs.registry }}/${{ inputs.registry-repo }}
          DIGEST: ${{ inputs.registry-digest }}
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY "${TAG}@${DIGEST}"

      - name: release
        uses: actions/github-script@v6
        id: release
        env:
          RELEASE_NOTES: |
            ${{ fromJSON(inputs.release-info).release-notes }}
        with:
          retries: 3
          github-token: ${{ github.token }}
          script: |
            github.rest.repos.createRelease({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              tag_name: "${{ fromJSON(inputs.release-info).git-tag }}",
              target_commitish: "${{ github.sha }}",
              body: process.env.RELEASE_NOTES,
              name: "${{ fromJSON(inputs.release-info).git-tag }}"
            });

      - name: annotate the ci run with container tags
        run: >-
          echo "::notice title=Job: ${{ github.job }} / ${{ inputs.job-name }}::%0A
          Pushed release container version ${{ fromJSON(inputs.release-info).release-version }}!%0A
          - %0A
          docker pull ${{ env.RELEASE_TAG }}%0A
          docker pull ${{ inputs.registry-digest }}"

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        if: failure()
        continue-on-error: true
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            :no_entry: ${{ github.repository }} / ${{ github.job }} / ${{ inputs.job-name }}\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>
