name: Charts

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/charts.yaml'

      - '.github/workflows/pr-and-release-charts.yaml'
      - '.github/actions/pr-charts/action.yaml'
      - '.github/actions/release-charts/action.yaml'

      - '.github/workflows/pr-and-release-repo.yaml'
      - '.github/actions/release-create-labels/action.yaml'
      - '.github/actions/release-determine-bump/action.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/charts.yaml'

      - '.github/workflows/pr-and-release-charts.yaml'
      - '.github/actions/pr-charts/action.yaml'
      - '.github/actions/release-charts/action.yaml'

      - '.github/workflows/pr-and-release-repo.yaml'
      - '.github/actions/release-create-labels/action.yaml'
      - '.github/actions/release-determine-bump/action.yaml'


permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  charts:
      uses: ./.github/workflows/pr-and-release-repo.yaml
      with:
        job-name: charts
        comment-release: true
        release-tag-format: 'v${version}-charts'
