name: Renovate Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: "ubuntu"

    steps:
      - uses: .github/actions/renovate
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_SOME_TOKEN: "xxxxxxx"
