name: Renovate Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on:
      labels: [self-hosted, linux, x64]
      group: heavy

    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          path: .tmp
          sparse-checkout: |
            .github/actions/renovate
        
      - uses: ./.tmp/.github/actions/renovate
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_SOME_TOKEN: "xxxxxx"
