on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test-semantic-large:
    name: test-semantic-large
    runs-on:
      labels: [ self-hosted, linux, x64 ]
      group: heavy
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test-semantic-large
        uses: docker://harbor.ukserp.ac.uk/github-workflows/semantic-release-action:v3
        id: semantic-large
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          dry-run: true
          branches: feat/smaller-semantic-release-container
          tag-format: '${version}'
          plugins: |-
            [
              ['@semantic-release/commit-analyzer', {
                "releaseRules": |
            [
            {"type": "major", "release": "major"},
            {"type": "minor", "release": "minor"},
            {"type": "patch", "release": "patch"},
            {"type": "no-release", "release": false},
          
            {"type": "chore", "release": "patch"},
            {"type": "refactor", "release": "patch"},
            {"type": "style", "release": "patch"},
          
            {"type": "docs", "release": false},
            {"type": "test", "release": false},
            {"type": "ci", "release": false},
          
            {"type": "feat", "release": "minor"},
          
            {"type": "revert", "release": "patch"},
            {"type": "perf", "release": "patch"},
            {"type": "fix", "release": "patch"},
            {"type": "build", "release": "patch"},
            ],
              }], 
              '@semantic-release/release-notes-generator',
              ['@semantic-release/github', {
                "successComment": false,
                "failTitle": false
              }]
            ]

      - name: output
        run: |
          echo large: ${{steps.semantic-large.outputs}}

  test-semantic-small:
    name: test-semantic-small
    runs-on:
      labels: [ self-hosted, linux, x64 ]
      group: heavy
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: checkout
        uses: actions/checkout@v4

      - run: npm ci
        working-directory: ./containers/semantic/

      - run: npm run lint
        working-directory: ./containers/semantic/

      - name: test-semantic-small
        uses: ./containers/semantic/
        id: semantic-small
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          dry-run: true
          branches: feat/smaller-semantic-release-container
          tag-format: '${version}'
          plugins: |-
            [
              ['@semantic-release/commit-analyzer', {
                "releaseRules": |
            [
            {"type": "major", "release": "major"},
            {"type": "minor", "release": "minor"},
            {"type": "patch", "release": "patch"},
            {"type": "no-release", "release": false},
          
            {"type": "chore", "release": "patch"},
            {"type": "refactor", "release": "patch"},
            {"type": "style", "release": "patch"},
          
            {"type": "docs", "release": false},
            {"type": "test", "release": false},
            {"type": "ci", "release": false},
          
            {"type": "feat", "release": "minor"},
          
            {"type": "revert", "release": "patch"},
            {"type": "perf", "release": "patch"},
            {"type": "fix", "release": "patch"},
            {"type": "build", "release": "patch"},
            ],
              }], 
              '@semantic-release/release-notes-generator',
              ['@semantic-release/github', {
                "successComment": false,
                "failTitle": false
              }]
            ]

      - name: output
        run: |
          echo small: ${{steps.semantic-small.outputs}}