on:
  workflow_call:
    inputs:

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      slack-thread:
        description: "Optional Slack message to update."
        default: null
        type: string

      status:
        description: "Status for the message header."
        default: ':hammer_and_wrench:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for the Slack."
        required: true

    outputs:

      thread:
        description: "ID of the created Slack thread."
        value: ${{ jobs.slack-release-thread.outputs.thread }}

jobs:

  slack-release-thread:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 5

    outputs:
      thread: ${{ env.SLACK_THREAD }}

    env:
      SLACK_BLOCKS: >-
        [
          {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "${{ inputs.status }} Release from ${{ github.ref }} @ ${{ github.sha }}",
              "emoji": true
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "
        <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: Logs>\n\n
        ```
        Ref:      ${{ github.ref }}\n
        Sha:      ${{ github.sha }}\n
        Workflow: ${{ github.workflow }}\n
        Run:      ${{ github.run_id }}
        ```\n"
            }
          }
        ]

    steps:
      - name: create slack thread
        uses: archive/github-actions-slack@v2.7.0
        if: ${{ inputs.slack-thread == null }}
        id: slack-create-message
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-blocks: ${{ env.SLACK_BLOCKS }}

      - name: output the slack thread id
        if: ${{ inputs.slack-thread == null }}
        run: |
          echo "SLACK_THREAD=${{ fromJson(steps.slack-create-message.outputs.slack-result).response.message.ts }}" >> $GITHUB_ENV

      - name: update slack thread
        uses: archive/github-actions-slack@v2.7.0
        if: ${{ inputs.slack-thread != null }}
        id: slack-update-message
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-function: update-message
          slack-update-message-ts: ${{ inputs.slack-thread }}
          slack-update-message-blocks: ${{ env.SLACK_BLOCKS }}

      - name: output the slack thread id
        if: ${{ inputs.slack-thread != null }}
        run: |
          echo "SLACK_THREAD=${{ fromJson(steps.slack-update-message.outputs.slack-result).response.message.ts }}" >> $GITHUB_ENV
