on:
  workflow_call:
    inputs:

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      slack-thread:
        description: "Optional Slack message to update."
        default: null
        type: string

      status:
        description: "Status for the message header."
        default: ':hammer_and_wrench:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for the Slack."
        required: true

    outputs:

      thread:
        description: "ID of the created Slack thread."
        value: ${{ jobs.slack-pr-thread.outputs.thread }}

jobs:

  slack-pr-thread:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 5

    outputs:
      thread: ${{ env.SLACK_THREAD }}

    steps:
#      - name: escape title
#        uses: actions/github-script@v6
#        id: escape-title
#        with:
#          script:
#            let title = ${{ github.event.pull_request.title }}
#            let output = title.replace('"', '')
#            return output

      - name: create slack thread
        uses: archive/github-actions-slack@v2.7.0
        if: ${{ inputs.slack-thread == null }}
        id: slack-create-message
        continue-on-error: true
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            ${{ inputs.status }} *PR-${{ github.event.pull_request.number }} Update*\n\n
            *${{ github.repository }}*\n
            <https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|:octocat: Pull Request>\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: Logs>\n
            ```
            PR:       ${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
            Branch:   ${{ github.head_ref }}
            Ref:      ${{ github.ref }}
            Sha:      ${{ github.event.pull_request.head.sha }}
            Workflow: ${{ github.workflow }}
            Run:      ${{ github.run_id }}
            ```

      - name: output the slack thread id
        if: ${{ inputs.slack-thread == null && steps.slack-create-message.outputs.slack-result != null }}
        run: |
          echo "SLACK_THREAD=${{ fromJson(steps.slack-create-message.outputs.slack-result).response.message.ts }}" >> $GITHUB_ENV

      - name: update slack thread
        uses: archive/github-actions-slack@v2.7.0
        if: ${{ inputs.slack-thread != null }}
        id: slack-update-message
        continue-on-error: true
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-function: update-message
          slack-update-message-ts: ${{ inputs.slack-thread }}
          slack-update-message-text: |
            ${{ inputs.status }} *PR-${{ github.event.pull_request.number }} Update*\n\n
            *${{ github.repository }}*\n
            <https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|:octocat: Pull Request>\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: Logs>\n
            ```
            PR:       ${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
            Branch:   ${{ github.head_ref }}
            Ref:      ${{ github.ref }}
            Sha:      ${{ github.event.pull_request.head.sha }}
            Workflow: ${{ github.workflow }}
            Run:      ${{ github.run_id }}
            ```

      - name: output the slack thread id
        if: ${{ inputs.slack-thread != null }}
        run: |
          echo "SLACK_THREAD=${{ fromJson(steps.slack-update-message.outputs.slack-result).response.message.ts }}" >> $GITHUB_ENV
