on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      command:
        description: "Command to test the container named $IMAGE."
        required: true
        type: string

      container-registry:
        description: "URL of the container registry."
        required: true
        type: string

      container-registry-user:
        description: "Username for the container registry."
        required: true
        type: string

      container-registry-digest:
        description: "URI of the container."
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      container-registry-token:
        description: "Authentication token for the container registry."
        required: true

jobs:
  test-container:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: heavy

    steps:
      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.container-registry }}
          username: ${{ inputs.container-registry-user }}
          password: ${{ secrets.container-registry-token }}

      - name: build image uri
        run: |
          echo "IMAGE=${{ inputs.container-registry-digest }}" >> $GITHUB_ENV

      - name: pull container
        run: |
          docker pull ${{ inputs.container-registry-digest }}

      - name: test container
        run: ${{ inputs.command }}

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        #if: failure()
        continue-on-error: true
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            *${{ github.repository }}*\n
            *PR-${{ github.event.pull_request.number }} Update*\n
            ${{ inputs.status-failure }} job: ${{ github.job }} / ${{ inputs.job-name }}\n
            <https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|:octocat: Pull Request>\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>\n
            ```
            PR:       ${{ github.event.pull_request.title }}
            Branch:   ${{ github.head_ref }}
            Ref:      ${{ github.ref }}
            Sha:      ${{ github.event.pull_request.head.sha }}
            Workflow: ${{ github.workflow }}
            Run:      ${{ github.run_id }}
            ```
