name: Test Buildx

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  # Permission needed for the changes.yaml workflow to detect changes across the full PR branch
  # pull-request: write if you enable PR thread comments
  pull-requests: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  container-whalesay:
    runs-on: #ubuntu-latest
      labels: [self-hosted, linux, x64]
      group: heavy

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: install cosign
        uses: sigstore/cosign-installer@v3.1.2

      - name: forward proxy settings
        run: |
          echo "HTTP_PROXY=$HTTP_PROXY" >> $GITHUB_ENV
          echo "HTTPS_PROXY=$HTTPS_PROXY" >> $GITHUB_ENV
          echo "NO_PROXY=$NO_PROXY" >> $GITHUB_ENV

      - name: install buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            env.http_proxy=${{ env.HTTP_PROXY }}
            env.https_proxy=${{ env.HTTPS_PROXY }}
            "env.no_proxy='${{ env.NO_PROXY }}'"

      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_REGISTRY }}
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: container metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ vars.HARBOR_REGISTRY }}/${{ vars.HARBOR_PROJECT }}/whalesay
          tags: |
            type=ref,event=pr

      - name: build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          file: containers/whalesay/Dockerfile
          context: '.'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          github-token: ${{ github.token }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
          provenance: false

      - name: cosign image with key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
