name: Test Buildx

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  # Permission needed for the changes.yaml workflow to detect changes across the full PR branch
  # pull-request: write if you enable PR thread comments
  pull-requests: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  container-whalesay:
    runs-on: ubuntu-latest
#      labels: [self-hosted, linux, x64]
#      group: heavy

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: install cosign
        uses: sigstore/cosign-installer@v3.1.2

      - name: login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_REGISTRY }}
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          file: containers/whalesay/Dockerfile
          context: '.'
          push: true
          tags: ${{ vars.HARBOR_REGISTRY }}/${{ vars.HARBOR_PROJECT }}/whalesay:buildx
          github-token: ${{ github.token }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

