on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      test-flags:
        description: "Arguments passed to docker run."
        default: ''
        type: string

      test-args:
        description: "Arguments passed to the container."
        default: ''
        type: string

      registry:
        description: "URL of the container registry."
        required: true
        type: string

      registry-user:
        description: "Username for the container registry."
        required: true
        type: string

      registry-repo:
        description: "Repo within container registry project."
        required: true
        type: string

      registry-digest:
        description: "URI of the container."
        required: true
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      cosign-public-key:
        description: "Public key for cosigning images."
        required: false
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

      registry-token:
        description: "Authentication token for the container registry."
        required: true

jobs:
  test-container:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: heavy

    steps:
      - name: install cosign
        if: inputs.cosign-public-key != ''
        uses: sigstore/cosign-installer@v3.1.2

      - name: login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-user }}
          password: ${{ secrets.registry-token }}

      - name: cosign verify container
        if: inputs.cosign-public-key != ''
        env:
          COSIGN_PUBLIC_KEY: ${{ inputs.cosign-public-key }}
          TAG: ${{ inputs.registry }}/${{ inputs.registry-repo }}
          DIGEST: ${{ inputs.registry-digest }}
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY "${TAG}@${DIGEST}"

      - name: test
        run: |
          docker run \
            ${{ inputs.test-flags }} \
            ${{ inputs.registry }}/${{ inputs.registry-repo }}@${{ inputs.registry-digest }} \
            ${{ inputs.test-args }}

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        continue-on-error: true
        if: failure()
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            :no_entry: ${{ github.repository }} / ${{ github.job }} / ${{ inputs.job-name }}\n
            <https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|:octocat: Pull Request>\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>