on:
  workflow_call:
    inputs:

      job-name:
        description: "Job name to display on Slack messages."
        required: true
        type: string

      release-rules:
        description: "JSON list of rule dicts for what commit types trigger releases."
        default: |
          [
            {"type": "major", "release": "major"},
            {"type": "minor", "release": "minor"},
            {"type": "patch", "release": "patch"},
            {"type": "no-release", "release": false},

            {"type": "chore", "release": "patch"},
            {"type": "refactor", "release": "patch"},
            {"type": "style", "release": "patch"},

            {"type": "docs", "release": false},
            {"type": "test", "release": false},
            {"type": "ci", "release": false},

            {"type": "feat", "release": "minor"},

            {"type": "revert", "release": "patch"},
            {"type": "perf", "release": "patch"},
            {"type": "fix", "release": "patch"},
            {"type": "build", "release": "patch"},
          ]
        type: string

      release-branches:
        description: "JSON list of regex branch filters."
        default: |
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'main'
          ]
        type: string

      release-tag-format:
        description: "Semantic-release Github release tag format."
        default: '${version}'
        type: string

      slack-channel:
        description: "ID of the Slack channel to post updates to."
        required: true
        type: string

      status-failure:
        description: "Failure status for the message header."
        default: ':no_entry:'
        type: string

    secrets:

      slack-token:
        description: "Authentication token for Slack."
        required: true

    outputs:

      release-rules:
        description: "JSON list of rule dicts for what commit types trigger releases."
        value: ${{ inputs.release-rules }}

      release-branches:
        description: "JSON list of regex branch filters."
        value: ${{ inputs.release-branches }}

      release-tag-format:
        description: "Semantic-release Github release tag format."
        value: ${{ inputs.release-tag-format }}

      release:
        description: "JSON encoded dictionary of release outputs."
        value: ${{ jobs.version.outputs.release }}

jobs:
  version:
    runs-on: 
      labels: [self-hosted, linux, x64]
      group: heavy

    outputs:
      release: ${{ toJSON(steps.release.outputs) }}

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: determine release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          dry_run: true
          branches: ${{ inputs.release-branches }}
          tag_format: ${{ inputs.release-tag-format }}
          plugins: |-
            [
              ['@semantic-release/commit-analyzer', {
                "releaseRules": ${{ inputs.release-rules }},
              }], 
              '@semantic-release/release-notes-generator',
              ['@semantic-release/github', {
                "successComment": false,
                "failTitle": false
              }]
            ]

      - name: annotate the ci run with version output
        if: steps.release.outputs.new-release-published == 'true'
        run: >-
          echo "::notice title=Job: ${{ github.job }} / ${{ inputs.job-name }}::%0A
          Next release will be version ${{ steps.release.outputs.release-version }}"

      - name: update slack thread failure
        uses: archive/github-actions-slack@v2.7.0
        if: failure()
        continue-on-error: true
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack-token }}
          slack-channel: ${{ inputs.slack-channel }}
          slack-text: |
            *${{ github.repository }}*\n
            *Release ${{ github.ref }}*\n
            ${{ inputs.status-failure }} job: ${{ github.job }} / ${{ inputs.job-name }}\n
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:book: CI Logs>\n
            ```
            Ref:      ${{ github.ref }}\n
            Sha:      ${{ github.sha }}\n
            Workflow: ${{ github.workflow }}\n
            Run:      ${{ github.run_id }}
            ```
