on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  # Permission needed to author a Github release
  contents: write
# pull-request: write if you enable PR thread comments
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: print info
    runs-on:
      labels: [self-hosted, linux, x64]
      group: light
    steps:
      name: Print GitHub event action
      run: |
        echo "${{ github.event.action }}"