on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  # Permission needed to author a Github release
  contents: write
# pull-request: write if you enable PR thread comments
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  whalesay:
    uses: ./.github/workflows/pr-and-release-container.yaml
    with:
      job-name: container-whalesay
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: github-workflows/whalesay
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-file: containers/whalesay/Dockerfile
      build-context: containers/whalesay
      test-args: cowsay boo
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}