name: Sonar DotNet 8 Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-sonar-dotnet-8-action.yaml'
      - '.github/actions/sonar-dotnet-8/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-sonar-dotnet-8-action.yaml'
      - '.github/actions/sonar-dotnet-8/**'

permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  sonar-dotnet-8-action:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: sonar-dotnet-8-action
      comment-release: true
      release-tag-format: 'v${version}-sonar-dotnet-8-action'
