name: Bulk PR and Release Container Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-bulk-pr-and-release-container-workflow.yaml'
      - '.github/workflows/bulk-pr-and-release-container.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-bulk-pr-and-release-container-workflow.yaml'
      - '.github/workflows/bulk-pr-and-release-container.yaml'

permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  bulk-pr-and-release-container-workflow:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: bulk-containers
      comment-release: true
      release-tag-format: 'v${version}-bulk-containers'
