name: Release Container Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-release-container-action.yaml'
      - '.github/actions/release-container/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-release-container-action.yaml'
      - '.github/actions/release-container/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  release-container-action:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: release-container-action
      comment-release: true
      release-tag-format: 'v${version}-release-container-action'
