name: Renovate Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-renovate-action.yaml'
      - '.github/actions/renovate/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-renovate-action.yaml'
      - '.github/actions/renovate/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  renovate-action:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-repo.yaml@v1.0.5-repo
    with:
      job-name: renovate-action
      comment-release: true
      release-tag-format: 'v${version}-renovate-action'
