name: PR Lint Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-pr-lint-action.yaml'
      - '.github/actions/pr-lint/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-pr-lint-action.yaml'
      - '.github/actions/pr-lint/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pr-lint-action:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: pr-lint-action
      comment-release: true
      release-tag-format: 'v${version}-pr-lint-action'
