name: Repo Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-repo-workflow.yaml'
      - '.github/workflows/pr-and-release-repo.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-repo-workflow.yaml'
      - '.github/workflows/pr-and-release-repo.yaml'


permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pr-and-release-repo-workflow:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: repo
      comment-release: true
      release-tag-format: 'v${version}-repo'
