name: Notify Slack  on PR Review Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-notify-slack-on-pr-review-request-workflow.yaml'
      - '.github/workflows/notify-slack-on-pr-review-request.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-notify-slack-on-pr-review-request-workflow.yaml'
      - '.github/workflows/notify-slack-on-pr-review-request.yaml'


permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added,
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  notify-slack-on-pr-review-request-workflow:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-repo.yaml@v2.1.0-repo
    with:
      job-name: notify-slack-on-pr-review-request
      comment-release: true
      release-tag-format: 'v${version}-notify-slack-on-pr-review-request'
