name: Create Release Labels Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-create-release-labels-action.yaml'
      - '.github/actions/create-release-labels/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-create-release-labels-action.yaml'
      - '.github/actions/create-release-labels/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  create-release-labels-action:
    uses: ./.github/workflows/pr-and-release-repo.yaml
    with:
      job-name: create-release-labels-action
      comment-release: true
      release-tag-format: 'v${version}-create-release-labels-action'
