name: PR and Release Keycloakify Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-pr-and-release-keycloakify-workflow.yaml'
      - '.github/workflows/pr-and-release-keycloakify.yaml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-pr-and-release-keycloakify-workflow.yaml'
      - '.github/workflows/pr-and-release-keycloakify.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pr-and-release-keycloakify-workflow:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-repo.yaml@v2.1.2-repo
    with:
      job-name: pr-and-release-keycloakify-workflow
      comment-release: true
      release-tag-format: 'v${version}-pr-and-release-keycloakify-workflow'
