name: PR Container Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/workflows-release-pr-container-action.yaml'
      - '.github/actions/pr-container/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/workflows-release-pr-container-action.yaml'
      - '.github/actions/pr-container/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel early on pull requests if new commits are added
  # Don't cancel on release pushes
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pr-container-action:
    uses: SwanseaUniversityMedical/workflows/.github/workflows/pr-and-release-repo.yaml@v1.0.5-repo
    with:
      job-name: pr-container-action
      comment-release: true
      release-tag-format: 'v${version}-pr-container-action'
